apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: mealie
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:PDksBFJTYfyx/Qu3,iv:swrRDP7OJgbx9n0N9tq/7tiFNSGMOFq8OchfoK/JTw0=,tag:IpLyU8omatxSPJUt6vA/Wg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:D/9fqtOYiU60OqQhhjgPgMXlJLGioDBjUmt8,iv:VX/8Rt9Iuk16p5vHXL147M9kxFt1eJapBdVOoUAMbBg=,tag:x4aXTjAmPv9X0Cq6yZl1fQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:4rBp+lApIny+SnXi8bKPVQ==,iv:In7QQYP46zaLetucBwwC0p4YTH9jsbW8CZz2v9KMGws=,tag:eSENZ9TBqLDrsnz3ObtCrQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:P5J7u8n1,iv:j9gcEj3NUsD1YB2AHd+4o/ffUT4oon2+3xP8zM27OvA=,tag:7yG8PVNfonGl2eB1x9Aqog==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:8Q+mcDMTAdezXKa/DWrraOKyc8D7ystc5suj7xkoxYAj+c1Ava8V,iv:wLceM2sMIQkJwmZ05KlZ4B4FLycFJz5iL3yLGLuHNuk=,tag:mJyzv4dUF7S1cOoIu2dsxA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:eQY=,iv:GeWlX72p3477j1jN7HvBOIhJLjP/fC4RA5d5C3sOVgQ=,tag:ha+3PTSWda60AjlRb6IAbw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:HRp6FyIKzwdZHEPs2rQ3ELmesbCs3bIOR2q0HA==,iv:QQnm7Ll4q9r7pckZGt4BZJ+vhtlIUQhBt5K60glrqI0=,tag:/oeF0ezKVYTE4r+QYtpi/g==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:NHjLwifB,iv:3gc9Eixu+zodP4Rct+ojojHDAqwqSJ9J4/JfMkaS0gg=,tag:75/dbvlQaESyDMA3OPUqLw==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:rLsNmw==,iv:8aXdSFimmD5x9voC7eMWwiB/2n4IzxHa/EcvaxcusZg=,tag:toRf9z3aUYVPLvMvoh7Vaw==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:YipCW7PPMWpVMSyfgKPLTYtttxaYybnHnTKGp7pgGHDIMGAdpSYlQ1omFVP5Xut4qV+SEUyxdr5rIzZm9nLHEGuDCRWi3lXFlzahpl2EU60wyMQ=,iv:4572op6eT+S9GxdRfffij91ZIhcUrrYmbNLul5sS6/c=,tag:v6Ab0YEae8hNLxUmImuNdQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:ULQqG+Rjghfh9XL2b0UkOLE1abHI3IvelUd8+PcNLp90TL+S5Sz6LA==,iv:46YX8r8aTxGk5ZylVODJsYautSzU1XciH49wX+fkIdU=,tag:9ss4UJ4tKYCiyUaqQrFc3A==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:97z5VARWsQFtKGEX,iv:0JhRZni3MDDuE3aDZtc0mEPEz0XYFH4I8sOA1/kYUcM=,tag:Gy/sdbexhgiKtanN1PwvyA==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:wk4wYEs1UuuC1PoL+g==,iv:aPhUFv2xW7eBjOiDxiMLmD7yd4+CwNmg3Vwf/cclby0=,tag:kSV8f6DRxd4IRrne/o3GYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T06:44:00Z"
    mac: ENC[AES256_GCM,data:iEIe4sLqjXU7EcQsf2oaaVMT48NJNzUH8LGzTYm8IU9ldiQtQSTk+hjctO22/bz5F2PV/BYTQR6MHg6YhBqhv8KQXq4nawXl8LNIoRm4QRvRJDwKR2uGX3/mFjVegRGnA14ASZP8sQo4AmAvbqRWNdw3FwZbweiQyTGOAE0CQlE=,iv:ijdaZ06X6BgY9ZKOjkcfkdlKY4TeDS8N8YaXVIumFsQ=,tag:Z2aZJC8VzIGxTqzu20Yf4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-init-db
    namespace: mealie
type: Opaque
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4GHr/nnesiQ5Lz9jOfd59SFZhEPwwPXJi+KNxY8F45/QnouXwZaDKw==,iv:oRKdX+Z6STtVLPg/14EdTbDwEGgmvw78A6IyG1ghTNA=,tag:vLA48GKxJ9vUHgXbNcPSVA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cy9cjGM+,iv:upuoC0Zje1+Q+aRE1Zbj86iuhIZxa+j/oSz4dGwHM6k=,tag:XVbrTtLndXFMvHbx7YmXcA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:viEOgyHk7DUX1Btm5UA09FupJ87wJ0J9cr+mdaCf8A==,iv:i6cyN5nmUXZE1cbf5tM8VJxg1b+UJsR1wDlfMhh/nBo=,tag:+KNyT83Aklr/pLGMAhZ4WQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kX8DjB9vKHWaWK/N,iv:+hpOitmhgPKlCe04pDQFYvYsMLw6Mj7uh4puLW7yp+w=,tag:y4ofLbVsKPkSYfUXoXW0ug==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:h96pGifcIJmaWdm6S0NSxHioGMnnSc/BSfwm,iv:Dzz+u4bRgpieAwDnqcnFgN0pggag69VslR/5QNFZ2gM=,tag:KUErI40eDulM2XIXr9/iTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T06:44:00Z"
    mac: ENC[AES256_GCM,data:iEIe4sLqjXU7EcQsf2oaaVMT48NJNzUH8LGzTYm8IU9ldiQtQSTk+hjctO22/bz5F2PV/BYTQR6MHg6YhBqhv8KQXq4nawXl8LNIoRm4QRvRJDwKR2uGX3/mFjVegRGnA14ASZP8sQo4AmAvbqRWNdw3FwZbweiQyTGOAE0CQlE=,iv:ijdaZ06X6BgY9ZKOjkcfkdlKY4TeDS8N8YaXVIumFsQ=,tag:Z2aZJC8VzIGxTqzu20Yf4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
