apiVersion: v1
kind: Secret
metadata:
    name: monica-db-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0zg=,iv:jjsUOvc+W0Jzsf3kaeP8XG/+OqN0JUnDl0ZCjhQc8xg=,tag:NHUfpNrgZ+/2YHZpAIEDsA==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:EKtKinKPmSQkttJ+HyEJB/bZXRvtiDaNdQ==,iv:LAI5S1YRwOoSiTuA7IiuadNVLeigQ0gjZx3BMqJ38e8=,tag:REPXUEYMygdHs0xPZR2LkQ==,type:str]
    database: ENC[AES256_GCM,data:l7hh9Zkxeu+r,iv:2VGt89Gi2zjnRBJNOlH7eCD2SLSEP1eeBzbXEg0jEcE=,tag:hHx3trtY6u4N8VrhRKW+RQ==,type:str]
    username: ENC[AES256_GCM,data:Q07YgzQ2pTKlIYMN+HD5HgE=,iv:/YWqrVUEBrCVsthrdyahzaaCwiAUFREmUE+n2DKvjsQ=,tag:tzHy5RaRR5+PQsU1EzME/A==,type:str]
    mariadb-password: ENC[AES256_GCM,data:CfTk2JiNJjGqKvfYZX3VIbnd2K2Y97LIvw==,iv:fjMHJ5RpOYTeTSIJDaAkMuznu5ryYG6iVj3BjtmkBOw=,tag:9xU9PyYoMwYCJq6mv10e/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T07:28:20Z"
    mac: ENC[AES256_GCM,data:PAHw84ivuW0++ioMNNlOK7gF1ERgZQHf10YAJlgHyGAfIchKeh/A6hppsTY5hUaAqpl5d2QieYWgKUAYTI9uZsvf70OjJqG3zec476KF4IWQogKv9O+GcmRc/sU8y5TBeb8+nMy5uB7dKt6iCRXBSTcu187yR2jKUjUgGVxurfo=,iv:h9ybPw1syEzL0pDMzUHarPOiBBnAB5k7/KD8XdRpETk=,tag:ppr2GlIb0bvovUfGv9deWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
