apiVersion: v1
kind: Secret
metadata:
    name: monica-db-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0zg=,iv:jjsUOvc+W0Jzsf3kaeP8XG/+OqN0JUnDl0ZCjhQc8xg=,tag:NHUfpNrgZ+/2YHZpAIEDsA==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:EKtKinKPmSQkttJ+HyEJB/bZXRvtiDaNdQ==,iv:LAI5S1YRwOoSiTuA7IiuadNVLeigQ0gjZx3BMqJ38e8=,tag:REPXUEYMygdHs0xPZR2LkQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:CfTk2JiNJjGqKvfYZX3VIbnd2K2Y97LIvw==,iv:fjMHJ5RpOYTeTSIJDaAkMuznu5ryYG6iVj3BjtmkBOw=,tag:9xU9PyYoMwYCJq6mv10e/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T22:04:48Z"
    mac: ENC[AES256_GCM,data:QfAY7dNVTxy5ERy1PrZBuzFRcuGFR9vV2Fyrrg75skvANxeUWJXYOhzAuDRRCH3i0/3+qOQq1ZfW5Irm3dtnMYc/3ZasneT981olf0AARt3q8fjoGUp+uwK+dE8ymgxGYU2V7mXUOTSY+vsJXOH2Dc6jfTfJUiKNHI/ltN1UcRQ=,iv:WNGSJCwcqpWBclsu5nhkrh1Ns37TOvxwHBpDkwAE6BY=,tag:Y/Maae/lIDEFa/If70yUEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
