---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kromgo
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/observability/kromgo/app
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_DOMAIN: ${SECRET_DOMAIN_2}
      GATUS_PATH: /talos_version
