apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:KlEdmqD4yM0X9+5abTw8rg==,iv:3EdFPP3R7IThxIqMbGHeqtK7gf79MS/X+Cz5mXBdSQE=,tag:pEbAKauMeifO/idJPeHcIg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:sTJa+eNpZp2oSC04odC70AN3DcYuQdou38A=,iv:sPD1x/z+DnicnHWOuzOg777m+LLrfMJ5WWyRPscHM80=,tag:VF7f7dve+KkLN/glXmzPuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T19:51:22Z"
    mac: ENC[AES256_GCM,data:d7CNPmCyXTwIubm0FSH2it5QiS6SPNN4LsGhMlqPVpgzzsDTIPF87k165PQs0jTneidZS8JASHegG5GfSDzeXV+R8HW63EGCTtmeIDJvaHHpQa4JdYU4FWD6nZB1qwQTWzRvHCYNXJwER2ZfKw4xWA91VB0o1LqZK48UPrDMs6w=,iv:TwjXOR4O06ij+/2wW86lCLrU7vdT7wT3yhUdIsydUlE=,tag:mxFM2UvGQN8B9ExLdZBoyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
