apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:KlEdmqD4yM0X9+5abTw8rg==,iv:3EdFPP3R7IThxIqMbGHeqtK7gf79MS/X+Cz5mXBdSQE=,tag:pEbAKauMeifO/idJPeHcIg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:K628uDHWOMtW+RA+vDTKGB5L4eqQ4ax46pQXJvg=,iv:6XYf+UR4oMWA63v2hUPfLhhKHUxw0aCCndmrWGpcO0I=,tag:GsIQ0SJmZxxDMuIe3oNszA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T17:01:19Z"
    mac: ENC[AES256_GCM,data:18OLGAfd7kFliRSlVCFZyz8LvrwSrWZIWlPh9mV7Wf6RimJ0Ssr0v59fDl9ir9QbAxOtg915xOm1f1pEoYPdVtgy1CZopusgYFYDXosY/eqDSRNKHgEcYDs+1imUJ3ZxQbqD/RZyZlWuISHdyqf5f6maQoINdsYPAzXyYxFvt0A=,iv:RMAiz3IkdU9KpIHdRDspAceCtYcjNL1/dBHgnNFfJBw=,tag:GgGNkcspGBW1pwkwpcuGhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
