apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stingData:
    RESTIC_REPOSITORY: s3:http://minio.minio.svc.cluster.local:9000/volsync/${APP}
    RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
    AWS_ACCESS_KEY_ID: ${VOLSYNC_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${VOLSYNC_ACCESS_KEY_SECRET}
