apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stingData:
    RESTIC_REPOSITORY: s3:http://minio.minio.svc.cluster.local:9000/volsync/${APP}
    RESTIC_PASSWORD: ${RESTIC_PASSWORD}
    AWS_ACCESS_KEY_ID: ${VOLSYNC_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${VOLSYNC_ACCESS_KEY_SECRET}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T21:24:31Z"
    mac: ENC[AES256_GCM,data:PxiIJO54vASi+CYYWJtHnpkUpyhi+t55oOzyfR1gsfDjFCLZ4pDRsa2m8m1kd8lLmwdIw76thYWFfhhmpgPDZSPvsXQHUQbCVfDnHMTjw6UXgZabXk/IofMsEedDpaE0XEN28Rd31NmX5YRbmkjKktyXr2Q2tqDfNLBPfb5N+vc=,iv:jp0e4MzzBWqiNeWJtgvxxDP3dic3Mxln/LtNn2QJ7hA=,tag:2P9sykTfvmvxw+Cg/i28Xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
