apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:04lbHHVcj8vDGtEol8PxQ/0iyfa0D1GwAYumJQcpSO8hIwTHOayHQnOGwbgHNA/0j6wVAzdz4PH5ALA=,iv:TDWY9aQTUYN4FMrmFYqEk5W/Y6Ihhx7nQhHsiB9yq0A=,tag:lGVejMnlTYC8wl/T9dX2+Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RfKVl+mITSJ0l0ERQXfp6zHsD1p9iFiPvjo=,iv:nkFTiieinILbDTEy8nkx77uvk/UF3Ar43cVufE6c1i4=,tag:h4wlCbY+k5NlI+0g6o/l2g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iyI69wU/gY4YVQ6/4qmsXrzCjp2UuYlm,iv:XatzWTXDUZrQAgizCB8qBkgkE1QDuPNzN/yHGnbi1m8=,tag:WyPJprAoEN/6UWUz4SnshA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kvhk1/YdBtwwPmwRf2rUYrIiToxCw4nQl/zf+Q==,iv:099V3J3PHCYEUywqU7iMgdSKQrqLanwSuZjQG/3JxJg=,tag:MMyrCCqfyBUoKTsgeARWfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T04:57:45Z"
    mac: ENC[AES256_GCM,data:XEV7IoGdKgU2Ue9yE/mDKv0EbhRLkWhSzMgPsqOWjWwW/jTpHM8o6KTA21hFxQVq62KkuL/+TK3lu8FVzpVGiovRInqLwriDm9SeOCYplSjOEOdPiX5tHP4YG7b/GIm7LCB+LotPdHM2DFWKAP4dQxScH9fPZIucXnzf5hUnrpo=,iv:ZoURI3sxLctC0to6DMnSprf/4Y+2wpAogeo1yrRW3aw=,tag:u2aWBkx0fPaMeSprmZOrEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
