apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stingData:
    RESTIC_REPOSITORY: s3:http://minio.minio.svc.cluster.local:9000/volsync/${APP}
    RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
    AWS_ACCESS_KEY_ID: ${VOLSYNC_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${VOLSYNC_ACCESS_KEY_SECRET}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-11T15:21:15Z"
    mac: ENC[AES256_GCM,data:4qQFbc+qUkHy9Dg7wjuWwqt9SustrEQeWDH/HgwpLBipB6OcyR1dn4is9b6yLLbAjJLUPkJVUjzq/sXDupnqTC0suoZBCqmNvxOJw3GeYc5r9GfsYnD/od9W56TAC0EZqVFKHPREoJ+LOvyYoRRguHbiCViiKTOl4oTWaGXreYQ=,iv:kutJnapWf2swF4yDNpqpgPS+1qk647yQjVO+6lkv80c=,tag:9fBEyc+rUatikX7nzpAB2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
