---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5

  values:
    controllers:
      home-assistant:

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.10.4@sha256:408a5a63e3e9a89ceb6ecd98345e54c86073314b4d94e217cd54f7208307406d

            env:
              TZ: ${CLUSTER_TIMEZONE}
              HOME_ASSISTANT_EXTERNAL_URL: https://hass.${SECRET_DOMAIN}
              HOME_ASSISTANT_UNIT_SYSTEM: metric
              POSTGRES_HOST: ${POSTGRES_HOST}
              POSTGRES_DB: home_assistant

            envFrom:
              - secretRef:
                  name: home-assistant-secret

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.95.1@sha256:d9bc7797d997e1b199e333676732e075bac4bae276dc0fe1baece2e313edfa09

            args:
              - --auth
              - none
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8080"
              - "/config"

    service:
      main:
        controller: *app
        ports:
          http:
            port: 8123
          code:
            enabled: true
            port: 8080

    serviceMonitor:
      app:
        serviceName: minio
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s

    persistence:
      data:
        enabled: true
        existingClaim: minio-data-v1
        globalMounts:
          - path: /data
