---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5

  values:
    controllers:
      home-assistant:

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository:  ghcr.io/home-operations/home-assistant
              tag: 2025.4.3@sha256:a9288407a81e19b67b9155b1ac4e0273e10492be572008dda38cf0f311a18722

            env:
              TZ: ${CLUSTER_TIMEZONE}
              HOME_ASSISTANT_EXTERNAL_URL: https://kaseihu.${SECRET_DOMAIN}
              HOME_ASSISTANT_UNIT_SYSTEM: metric
              HASS_HTTP_TRUSTED_PROXY: 10.69.0.0/16
              VENV_FOLDER: /venv

            envFrom:
              - secretRef:
                  name: home-assistant-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.99.3@sha256:e822acb286dca144f1a10ef847bc8f905d92ea79998f4f021802064badcae5fe

            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8123
      code-server:
        controller: *app
        ports:
          http:
            port: 12321

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code-server:
              - path: /config
      config-cache:
        existingClaim: home-assistant-cache-v1
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
