apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: minio
stringData:
    #ENC[AES256_GCM,data:asSP4w==,iv:giWjO4JiLxJ0Y5bCKsFNimEI998cTbbnNO+YRj0tzcs=,tag:sFlAbftlGftCL5Wvg54oJQ==,type:comment]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:8cJ8xQ==,iv:xmswedpQYkTUZ6rvjvVX5PvaRr6S4jvk5iTWdUbIYuY=,tag:Ixd4Lggd2lG8GB6U9jSp5w==,type:str]
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:JkcWyS8E01JfQv14QKZ3b8s=,iv:O5tQ35gw6S6WM7MF2jvPIiPHB9PAA/J22CGWd42HhBU=,tag:eofDvStH0xBmSaTDxvz4fw==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:J1aHioeiR8EX3sZMxu4/YWg=,iv:rw/oxqVB2DUJp8D2kwa3ntQ1063RZ5k0pjIjVezeJtg=,tag:dkkq2t6sh+MnlKngtwl8cw==,type:str]
    HASS_SECRET_DB_URL: ENC[AES256_GCM,data:xGLhm87B4xAYrWfwjkQq2gpVRbdklHRYpHdFapJ6vwH63VSKG5mii/Bkf3ldCrSBOdP0dSV+vWG5oA21qcj1WM1yNYCsw6zuRXz6Iez7oOCm3u3pQxCyHjPEQy4w5+n7EXrf+mCvlUThzb0eoK8=,iv:fCFtyOiw0cBg6ZRvRXGLF6jnUNr1j+Ie6Jq+qqHrCKc=,tag:BKY3HeFZkDnaPZxDzLEhbQ==,type:str]
    HASS_SECRET_URL: ENC[AES256_GCM,data:2OGD2IuBxoRiJQCzmxHM,iv:yu0hJcbe5IgwSfcfVJZlqawAj7vgWQhz+sYb4RrtobA=,tag:qYYjIsrIJSiIuLo5XFWVAw==,type:str]
    PROMETHEUS_TOKEN: ENC[AES256_GCM,data:tNPILclFtD/6hqqd/opAl/+E66qt0JY=,iv:kiyK9OU0CkksRTXsCyM2rzilCS+as6Pj4bpG7cHUko8=,tag:yVyiHLBPikOj/g4AeaODSw==,type:str]
    #ENC[AES256_GCM,data:WGulGDnWBbrsUYzxJ/A=,iv:qvmPcZDY+46luo24Mnp7ZofyRWSbP54C2DRAsXu9/Vw=,tag:F/NocJMJBjSLcAt/D6ZsDQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:arnykTr85H7LOjLXoVA=,iv:W4jTyQmdtubQ6EMgatITuj/71Li09rhvayWO8pXJprU=,tag:k1WSc0mSxelZCcGWPjMrxA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:6Oln2+TMHaAuLPkI++bZdXWzcGDmm4xfFz3kv9rjH++8OfBQbAAL6g==,iv:NjLVv15WAeC/9CcxrThRRg/T+IpNiM0vvii6j9oMKlU=,tag:pV0u3V3d7HBcWuVrOBweTw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:WdcvRcijq6xSmPmXKushexWTa4Y=,iv:ok8Q7RmUIvpReZTJ3cpUXoKTOoLOKI0jOaSHXkufgHc=,tag:vm+251ZIf+NXKzVltbw4pw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:slC4mZH359id693JcNO8DJyqrnY=,iv:6UNOovYXCSL5MyEF+zGROX0mX1l5vzjVwJLnecnwNFk=,tag:OTUGEMvLVpuhtFZLTDvZ6w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ymD7DZSOWZxC7PmsBqvN6pqXRhmauXvHEOw=,iv:9VZZaSRFgh2Cneu3WoVRPkv/LgzXtNBQ3AkNNSCEQaA=,tag:queW9u+A6ebBRa8UIarzXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:19:15Z"
    mac: ENC[AES256_GCM,data:vkyIQh/sF64m4Y1Cw69h38ukzQnuetedotnC0nuTeuM52A8Ioa+fc/ajQBQNzMDPUgCINLXN3XGvCNRqlkyg4Wo/GE9Q690M373sZ/3jX6/RuZRCHFHcxFZ/voJBjcrWPnUCtsMG3FkCIwXHcN1FQfiInahtj+UoAMj/nJiZ8c4=,iv:KCO9DJbOZrTe0WgssyErwSX3KfmfwMK6bVf1EtB5qa0=,tag:WxWnWJFxF4nfS2CIgAGBjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
