apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    #ENC[AES256_GCM,data:asSP4w==,iv:giWjO4JiLxJ0Y5bCKsFNimEI998cTbbnNO+YRj0tzcs=,tag:sFlAbftlGftCL5Wvg54oJQ==,type:comment]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:8cJ8xQ==,iv:xmswedpQYkTUZ6rvjvVX5PvaRr6S4jvk5iTWdUbIYuY=,tag:Ixd4Lggd2lG8GB6U9jSp5w==,type:str]
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:JkcWyS8E01JfQv14QKZ3b8s=,iv:O5tQ35gw6S6WM7MF2jvPIiPHB9PAA/J22CGWd42HhBU=,tag:eofDvStH0xBmSaTDxvz4fw==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:J1aHioeiR8EX3sZMxu4/YWg=,iv:rw/oxqVB2DUJp8D2kwa3ntQ1063RZ5k0pjIjVezeJtg=,tag:dkkq2t6sh+MnlKngtwl8cw==,type:str]
    #ENC[AES256_GCM,data:z0u3f3cizU7B+B2XabfHV90MTIuBJShLwmcUWT+hKPG4StxImigu684vGRXidV2fd9/3I6GQacOILDQ2VkB6B9+oHoOn0O19/2L8WtVMYo/21xMyTGr1HiMo57vdG8CWzFCq7FF/CzaBbKajVrNrk950yufCG2Wq4qidVpnhcfNx0W3nKmY=,iv:8y3BZPacNG4fJfHmXgHkCy5sKvIo0QGE08j6q0fpjso=,tag:IjjigGxtC0ny7YdKJ4eExQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T05:52:06Z"
    mac: ENC[AES256_GCM,data:/ljpV4rlEMevlKsBzT5DJ2YrHdj+IK/IBoQmPYMO9O+i350nHuTCV76nJc20DGmynKQTM9gkaRWMkCL6ljJR5IcmY31KqTiw/g7JPvEfe+KOaHn1DQep1b8L2trZCs6oZKyZmHdl0WfVDl7cmxjgyUUIJOtJwEQS/Wqyh9C2phg=,iv:LERIGquVjrKoIEZhofGuhnnhqwcSFRKZDfb6EtBSoIY=,tag:xAolH/FFeTnUzqd5GRPe0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
