apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:9D3CJP5iF85guan+ZNFYFwcrlR8G,iv:CXvDtbbeg3UxpYeLGwsju/WXAo+X5UMGri5aS5xi1F4=,tag:b7Qw+1KllR2RIzUn7Vj0hQ==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:O5vBXmmT4P2eZ7+ZWhgr,iv:LYpbWgEn65h8LL+C/HhFN74DnY36ygy21XXfZ+VKWkw=,tag:z2BtYrwkaW4uP9XlBDJQug==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:8g0etKu7K5F/QzhM0Z1xHjf5KTtf61V8,iv:VjDCs3r7wKeak+9bzfrdrMMuOvL4Zl5pL4OHt2Eg5sY=,tag:oi3h883MOiStgbuOgmojOA==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:5ljHhT/rDRS6CWXKGbpHM6iFVGNS3z5i,iv:8fvLAf/Z/vXCxhTE2vMaRSqwfDASnTKusZH9eTjFJ4E=,tag:IvbDZ5IDWMmPLwSXC8HpBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T20:06:33Z"
    mac: ENC[AES256_GCM,data:emjaQUssBW3lvSOvkaWuNzD3ioD43Ie7WJ1ls4gY1QfpaS3bNjyPideO78VwI1EdH12hpkqVsIu0NWx8ZFc8t/kB9YZhysi0Baj34sfo1Jtev/OTdclaTmRODFExWJRD915W+U95DBE427r9NU/swwueD5Xv01NeAJBP206fCh0=,iv:L8+k5Smsy/UqcsEcpoSYsMmuZtJdjzj1ATwi41TMzQE=,tag:/uvoT37eLQBDYGIzKqx79A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
