apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:QoT90PXBhFJRy/ovQlgNn7XKXzg8Dl2rXYed48EyYc5+jKXb9IPmtkFqfi8SQG5/AjN6PaV6bq5LyNZ+aqJ3B4WdjCWpsMw6n/DgqGo8k3ogzm65FOISneFSbZg1ENrwXuMZ/TUOys9Iqauz5HA=,iv:TXKdaPJ3CTcsI5QUOtm91cEOGnB3Dak54wcGhlsf//E=,tag:nIRHa9qAnM2XBSTf7ztA2A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:1EGB24ZeK1x4iXw=,iv:GeItJOliM+N6kQ+Ltiw2pV606rYiZdPeCjiOy2ipSFM=,tag:y9EOFxyIn5Sh8S5z0rZpdQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:wn0G88VuRobeQuqAMIyKryTa9qDZhzlwAV0=,iv:xSnI2BKGHn8InJOs9GdDgjkTBrepkkOkAyDt5ROihgM=,tag:sxvtzL1U3ZaiYsRFt3q57g==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:GphbciIJO/GeSoaqWoGn3GDhqr1HBn+lu4tk0cSELy5OXP7e1mirUg==,iv:RJ9QjQZ9J7PIqc1CtTJUI3SaZqAL/3Sexe+0VyRf3Xs=,tag:+IvCLXaPuecizR9PVYl4AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T08:04:57Z"
    mac: ENC[AES256_GCM,data:GPpTLn8XYlW+Cx4jiw43zy0wVu/hO4BdP0z24+NYLSGZXw3Iaw8flgWx7GzvjOF/bdZVkJw2Q2NgjwbcIYiKIVOen+OcsZ1+E9a2TZ7P+f7y40+vk7pDCKlbpDSFyYikRI4o+zIuwejMnAB974unCDM65OIUq3s8DXbCeDGFL1E=,iv:SbYHALzXQ9DWrjBfegG7iB1I3wnFQKes7SvRS3IOOMY=,tag:6D7vrPiPEwV5hka5R7OveQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XyytWFaQv8Dmszs+fsqHXQ==,iv:8XH35UBUEwj9mdqzxeP1oP2cwWhIVbIB1Wmk4fYe9MI=,tag:hsKiUA9oTaQeVjvNsPLvSQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:P3/Xrx4aaKw2Xv61GLgEEoQS8QOxEO47LC8tyeGgLDbLVKfuuw7gKSnReKtW1nhY6G/xET+BSwA=,iv:Qefdq7WSrYqfEv4kxQRvfK8nlDJHYurXw2ep1qql+GI=,tag:5wVKVKJmUNFUO8Ct8LIorw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:N3aCfSxxLbv2hNlG6/WxqA==,iv:YuSuWw1L/evqLE9+FkBfYr7LuPUmyieg58j7voAlOWc=,tag:Jenf70x8ldup1VbVV3uIeg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:twMGHrjB7lpbhdNFKGv1L9SEihmAx3mveQf7JkeTE6MAWQ7n,iv:fWkfug+uJFiOgOWqe1kpbPnumr8rniAs3QmFyGYe6ag=,tag:fEIXa8kDays+4jvaQ6rZiw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SMEkT2Jj9ndRmkZ8hJfAq/2gbYJwrQDylQ==,iv:gQi2T53QwclnZwI2H6dhyiXJIHELsnBsSQ37GZXQNGU=,tag:19Ce2ydJZC3z3nk0+/4Nhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T08:04:57Z"
    mac: ENC[AES256_GCM,data:GPpTLn8XYlW+Cx4jiw43zy0wVu/hO4BdP0z24+NYLSGZXw3Iaw8flgWx7GzvjOF/bdZVkJw2Q2NgjwbcIYiKIVOen+OcsZ1+E9a2TZ7P+f7y40+vk7pDCKlbpDSFyYikRI4o+zIuwejMnAB974unCDM65OIUq3s8DXbCeDGFL1E=,iv:SbYHALzXQ9DWrjBfegG7iB1I3wnFQKes7SvRS3IOOMY=,tag:6D7vrPiPEwV5hka5R7OveQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
