apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:MTbkVIx9+qhugIG/vbjn53fS8Eq7A8iodF3LJbNdACQIZfxbfSJsMkucwoXMd95iUYAetQC6OEl43iQ5wW4DYwqAmJZTvoDfAMl+IGwC8DbD+yw8empJ7UlcbkjpRUfYFJ344YM/gPooKd2jTigJx6DfnRdSpbE=,iv:6wOdbhDHr2wBr11gGoxmxducYnArdFxg+swmNtsUCfA=,tag:zHSWleKvhbru8rDBEreCBQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:s9wbxdpo/eKUGII=,iv:zNHf5SuUK75iBWyuvHQ08OFcJ/pps///3gBBiUjsFLU=,tag:+GnyQTRAYp0Z8Snrat990w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:eXLSwti1XjGIcrJqmG9GiWri70iaVJWByrc=,iv:c4fWo+Hfg3MojojMthlPccOkd8WIGSC1DXyAg23NmlE=,tag:Z54HHNks5dc52EoIMaQpRg==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:bzr/13GegwEUMLysI50Vs+S/7P9JIYKahIaGdemmpfWALyjyu49IFg==,iv:J4oAQee5IQMhwQ9Mrt19zbvc30opUVRuWWNwqu6x7Mw=,tag:/TaSTHQAonVWX3noxao9ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ0pOSjFoc1ZUTXV0eWVl
            blZrMnlvSWxUaHFnK3FWYzRmeGpYNTVkWTJnCjMxdTNZQUU4T0puZEZ5ZzA4TGtH
            T055UWIwMzBybjdTSWd6YWxCMjN5VDAKLS0tIGdwSmlRSWFFbGhtVnEzWnZNczU1
            N0VVd0hjclpGMEI4bkxhNlFaSEJOeUkKA4vVCuc8BEXCBG2GaQr7jt4QRY16OrKp
            6c77P4Zr9Wp6YV79LVTg1k1iBrGKizHZsnB1asCSr/xGTuTWsZD9Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T08:48:40Z"
    mac: ENC[AES256_GCM,data:Qm9wFw0Ok2s1dcNJ0nekAlguUAldqaGcBPykvq+xejBk0ZhPZscKhpmb4HzZ0pbXsTVKK0B8lUBeBnv1TxfI36+RESlZLDjjEJZ42mncp8BRsla6UjsmOymaHAfRIVsMX5uYAJ+320jezdSCv0kiKSR/rJwEd9OZUJWP8wCNEJY=,iv:REc4qBB7hBp+cUzgNPgsWo23H9KsKcx+Rp/ZXq5HcDo=,tag:L/lIwyg5bR+AFyKMECOU0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: vaultwarden
data:
    username: ENC[AES256_GCM,data:SKgMP+cHWn6pk7V3P8A0ynwuXqM96QCQ9g==,iv:z2G7ROYTtd9jmiYnWY+RTs4pRZ9mQLLcI9iQb523oNg=,tag:T5yw5vyD/YNBLcTmqiLPxg==,type:str]
    password: ENC[AES256_GCM,data:Tac/JpK5afXpDw1xZAjLmgcTLwHHcBkVqg==,iv:2GDtHnCFp5Uz4DJRq0WK6W44csoQLUh5O0VlTKB6jbA=,tag:/1wMLqXzQiNf0zZcIp8CZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ0pOSjFoc1ZUTXV0eWVl
            blZrMnlvSWxUaHFnK3FWYzRmeGpYNTVkWTJnCjMxdTNZQUU4T0puZEZ5ZzA4TGtH
            T055UWIwMzBybjdTSWd6YWxCMjN5VDAKLS0tIGdwSmlRSWFFbGhtVnEzWnZNczU1
            N0VVd0hjclpGMEI4bkxhNlFaSEJOeUkKA4vVCuc8BEXCBG2GaQr7jt4QRY16OrKp
            6c77P4Zr9Wp6YV79LVTg1k1iBrGKizHZsnB1asCSr/xGTuTWsZD9Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T08:48:40Z"
    mac: ENC[AES256_GCM,data:Qm9wFw0Ok2s1dcNJ0nekAlguUAldqaGcBPykvq+xejBk0ZhPZscKhpmb4HzZ0pbXsTVKK0B8lUBeBnv1TxfI36+RESlZLDjjEJZ42mncp8BRsla6UjsmOymaHAfRIVsMX5uYAJ+320jezdSCv0kiKSR/rJwEd9OZUJWP8wCNEJY=,iv:REc4qBB7hBp+cUzgNPgsWo23H9KsKcx+Rp/ZXq5HcDo=,tag:L/lIwyg5bR+AFyKMECOU0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
