apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:pXBDDuVpwc452WnjcCdsvDWtGi/oENIO4YEjygFiXoBzpgwTpceolxb70Td8ygJW+vIIi2Wed0qGV6iWJ4QpX1KTJD/0ABgwhr+S5qcFZzIKhQD4XcdlaP9HK1hK+XW3WJR0u6zAolgPr61XFhzbGpcBcMAVr0s=,iv:h4eWT3v0fga+OIhg6wn53BdT1c/6Qx14TFsIML5yYd4=,tag:t96EmsnHkNofH8+PMVEHqA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:1EGB24ZeK1x4iXw=,iv:GeItJOliM+N6kQ+Ltiw2pV606rYiZdPeCjiOy2ipSFM=,tag:y9EOFxyIn5Sh8S5z0rZpdQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:wn0G88VuRobeQuqAMIyKryTa9qDZhzlwAV0=,iv:xSnI2BKGHn8InJOs9GdDgjkTBrepkkOkAyDt5ROihgM=,tag:sxvtzL1U3ZaiYsRFt3q57g==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:GphbciIJO/GeSoaqWoGn3GDhqr1HBn+lu4tk0cSELy5OXP7e1mirUg==,iv:RJ9QjQZ9J7PIqc1CtTJUI3SaZqAL/3Sexe+0VyRf3Xs=,tag:+IvCLXaPuecizR9PVYl4AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:22:15Z"
    mac: ENC[AES256_GCM,data:T7Xan4oMgTkaLZcsUJYSZvLOpEI+AjUgkni1hvqfzfHfaTTt8A/Nd7P2gibYje/VKjkX2D8lhbBC7h+KHSYcG0xc/ehCyhVueILRDBvuck4I9PWSRIGVUsHqROnypGIubDVyKauAh0+57PeS09tPA4zxvCUIysC5Tkl2ia9WImg=,iv:LYLOqErkL6X+lHzd75T5gPWJTdQBkHhqjJ6EjTZJxAM=,tag:WRsgdf9Bchb6OUqsaHMxLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: vaultwarden
data:
    username: ENC[AES256_GCM,data:vSwVyMSbZpplsn6SPv3DNrczcZNGsCf7AQ==,iv:IwdVH46BTu9nEKRi1ocrVDwZeEuvAjOIXmAPlCaMjQM=,tag:OLuUpILobU6gTT1cGhBCEw==,type:str]
    password: ENC[AES256_GCM,data:yu5R9vIv2FMgeRBQ39ppfnr5iSIzTin39A==,iv:85NpEwbUVANa8A2bbcubOicntm3XSIFSM0J5gZlUohI=,tag:/MQq+NPJs8LjdDITgv5h8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:22:15Z"
    mac: ENC[AES256_GCM,data:T7Xan4oMgTkaLZcsUJYSZvLOpEI+AjUgkni1hvqfzfHfaTTt8A/Nd7P2gibYje/VKjkX2D8lhbBC7h+KHSYcG0xc/ehCyhVueILRDBvuck4I9PWSRIGVUsHqROnypGIubDVyKauAh0+57PeS09tPA4zxvCUIysC5Tkl2ia9WImg=,iv:LYLOqErkL6X+lHzd75T5gPWJTdQBkHhqjJ6EjTZJxAM=,tag:WRsgdf9Bchb6OUqsaHMxLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
