---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secrets.sops.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: clickhouse-logs
    files:
      - ./config/logs.xml
  - name: clickhouse-ipv4-only
    files:
      - ./config/ipv4-only.xml
  - name: clickhouse-low-memory
    files:
      - ./config/low-resources.xml
generatorOptions:
  disableNameSuffixHash: true
