apiVersion: v1
kind: Secret
metadata:
    name: clickhouse-secret
    namespace: authentik
type: Opaque
stringData:
    CLICKHOUSE_DB: ENC[AES256_GCM,data:pOG6Y0DqzEPi,iv:Tz3T7TpK84RAMNjuWeHIcOFk9robbRtXUDxdqVar1VU=,tag:xnr1gjM9D9+bAisIc1zBtA==,type:str]
    CLICKHOUSE_USER: ENC[AES256_GCM,data:dHBIbl/sZ17s8A==,iv:8G1fZnzgW8EjD1njIjm/GpjNA5v86BUmwLleWnRgzfs=,tag:hT+GbBExqF8PlF1tuJgW1w==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:p4uo0V6ca4HyeddNMv2yZmbfP852Mm1vIA==,iv:TLoWwArRqccLlWPdW53T59/1L3XiuNHnfAgfXaWMCrQ=,tag:92D9SG9XH+WNHRyODAmprg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T23:30:42Z"
    mac: ENC[AES256_GCM,data:Twa1twyOUuUAx7JBAvYSjGSm3HP2aoma8kQKOvg02jTZalMs+ZzJpqsIjARmlXYO5Fdxap4i30puz5V1rvD6TQSPOAxGXpYgOKHbRdhDf3DsXQT7FYTEbbw6JVv6BJTF7ph+yYKabGkKxs/kjBIAY6Az1CPiFa9jsp4XZsQmaek=,iv:aXmIAUzXjVGdWMu9lvTloWFv8YjUUM8zTvNUXIPe338=,tag:cdmgJY/d/8L0HQUTSbUFTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
