apiVersion: v1
kind: Secret
metadata:
    name: odoo-secret
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:RLm3Dg==,iv:v2g9KjM/gJ+gI07ex/umhtfF3TJINPS72YqfTJXmQd4=,tag:jT/VWAW9I8sj7O4SoTiHCw==,type:comment]
    HOST: ENC[AES256_GCM,data:GRrQbR7eA9TPm2qfOVGAkpEwzg==,iv:Wzf4vxFXAiEIvEM61aV3ENWIanUvcwFIcKh9dXWUuBI=,tag:2BZ7ZhlivLF57UUWMqyCeA==,type:str]
    PORT: ENC[AES256_GCM,data:g9DSqQ==,iv:jswft5KU1Q2iCTB+8A46W39olXdLdDAz1tTVAc/iyQE=,tag:++Ki0XMxDkf0SWJkbcq/Ug==,type:str]
    USER: ENC[AES256_GCM,data:MGxpngKaZtaeuw==,iv:Z+YAkPPh9wIxO7Cm9NyFHd3uF9Mm50XBEg7qTzIEzcU=,tag:yXShdxuF8lizeiHonGvXew==,type:str]
    PASSWORD: ENC[AES256_GCM,data:zLHT14VrH6T9jbxImAG1hYwlU4rkuqK0,iv:Wt/crCCowVeiJKJWLzOLfBzl91TM3g4dhfHDKiGf/Rw=,tag:m5sVbKO9U1bbuf4b6bDWTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T09:37:42Z"
    mac: ENC[AES256_GCM,data:MJ7UlwpeMZ+eJ/4JSZZQgEKtdty7W3CLCvYM9P8hhroJZeILBMV8Xts5p1w60VPwyTPgEq+FqA1ep3pFiaqsjIODSfWlV8cRnRwhn5rs1QNI/BIzgbT8eQJcTfUo6oCsKWPDmVgnHSn572KLe5e5FEcwwxN3iDTV4h/g4cdDPq8=,iv:Ogbo/5wP+5GXjJWbLuohkOKt5Cdf6Cq4hvYmB7x7GfY=,tag:Y4SExoHOXHqZ9KCBz+mUiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: odoo-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ZvXHUHXKqqA=,iv:NP8M/nyJRu4rLCb7QPwoJBQ+TGf3Ln/0K17sim8dMZg=,tag:fO8sSpJJEHYiU6TOfLR84Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:igBYfmxrB0pSEJsVlnnjmLgoe1EXXMBXIitKWgV5BDmW2Ie0dqvzJnF5t8y9bJEiXLh42GBk6Dg=,iv:2Og+0li4DZw2Jab1UK5EmJu2Hiv5ujUxvFJRISH/8gc=,tag:9VWfQLKXjz0HMBoJZhfXwQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4P87KyNMG8ECCyJMyunS2g==,iv:QQYjdtdwQiYsX1IkfwSaC2mWBXd4aL1SFonou4zZJL8=,tag:eDouTe825ir8opvpB7JS1w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OYLO0Yv9AaZy4dZ/cf8+i33FFeZB+yDhIlSO8snmMSg=,iv:YMCBPQLdNfl1ohHmQc9jEchkTQZCTnizxdakadTJ+FI=,tag:ZKNapr/RwpWTX+3xge9urg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SMEkT2Jj9ndRmkZ8hJfAq/2gbYJwrQDylQ==,iv:gQi2T53QwclnZwI2H6dhyiXJIHELsnBsSQ37GZXQNGU=,tag:19Ce2ydJZC3z3nk0+/4Nhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T09:37:42Z"
    mac: ENC[AES256_GCM,data:MJ7UlwpeMZ+eJ/4JSZZQgEKtdty7W3CLCvYM9P8hhroJZeILBMV8Xts5p1w60VPwyTPgEq+FqA1ep3pFiaqsjIODSfWlV8cRnRwhn5rs1QNI/BIzgbT8eQJcTfUo6oCsKWPDmVgnHSn572KLe5e5FEcwwxN3iDTV4h/g4cdDPq8=,iv:Ogbo/5wP+5GXjJWbLuohkOKt5Cdf6Cq4hvYmB7x7GfY=,tag:Y4SExoHOXHqZ9KCBz+mUiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
