apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:jOlRgkomGpFSkH9c+gZXEOxL1F4/16W2pC65WXZ1xHWin5ZB5ZCjtuPetShyH/giQD8CMQBH6xmcScvbFgV5Pqdxl68nUrQzGfo7/0//mc+ErWtcBja4Mk10doz9CjQt+ED9upVDuAkNb+FDN8IIwFAxvsD8hCRTXL5zp53GrEU=,iv:mAsETJV+d0LsRG0DBhTcjfcWalg/+vjHFT/dyUPhFYk=,tag:Wci41zPlqNEyBt8c6UCvlA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:7ECtHzWwS5CjGQ==,iv:6M8GstaCzcSPeYsP+avChjWgTTl9H6GVBzk9If2SJ9I=,tag:agpUcL5WclpxTWQmbE16nQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:O43crb/T3kZCphB19c8sLA==,iv:YFQNiQgGhV547ozMSniul0KOgJ+9jQqJY1XLSgXt8GI=,tag:OiF+Pgl8SP2C5pffjkGlkg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NJB5SEtgoGFxtoGQv1OOs9n0yv3Ds83tjQ==,iv:UbHC1vzWOWmKGAK4Q8Xk2flGIbDap54zEE2dmg5gCEw=,tag:SM4tehXOSkgRzQiQiDDT8A==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:c1YE77W55cWKFTE1Gl5bkuPfrXbkLWmpzCKobBPR5vbNdY5/JFPVtgavxC1zacwhVege3aSpkY/u/pRXcGUAYw==,iv:LlMsrh6ayqw5wmhiuP1on47r9oUxqz16d/OVnIPOrhY=,tag:GoWPJXNo7Fzreh6xy6mGMQ==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:COhvXKCX6qb+ljmBFuzsRVoTDfO/RiZrSwxU3sYQgqOjVc8WV9m5cawN/hggIAVfzlFAcQbnZzd3ZIQAwT5Ajy91j5b8teBlpOvy5ZJIcltWbt/w0IxTdmvT8gE59RRFh3BizhO6NtGmx3AwRynuXHnn3JASEfq5w8XaHQYXuoM=,iv:cy06I4p5rcdm6P9KvRlA+Izij9M134Q8ovt2DoRTuY0=,tag:Onr6MHoG5AiLNnS5pRIEqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T07:56:47Z"
    mac: ENC[AES256_GCM,data:IhUEHgWfbyWkI3qgJSrTR6neuI7zWe9F1D8/dBJ6o02FSAZvtmr2pcONBZhQqVzheTwakSHZ7lAaaHp9DRBSLR6TB/Tx45OD50KRH028rqtODu7EORXRhPVesrYo9a0+si81ealr88n0YyJusu0v1VXJ2IAek74oWK/+YqtIwGQ=,iv:49Qk2BrcVg0TWe3YhKQcd6OhFS2db3IoIRQdv9kRS6k=,tag:gPAo7jGpTEJLwyzXPGH1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:rU+KcFICoSyxebaj76oeiQ==,iv:wycdGQ7zSK60AcRk1OZt/9n5xOqmrlSukt8eo3x9st4=,tag:/dowxjUKHgUv5Qw9frkLdQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SwMYe2Ngs+BO4vokTxQmUcYm0MffMwpXSpY+z5wPo9w5kfGBbdFNE9f2huPn70QqrSrsXS2eRqc=,iv:YlO7j4pn98ypm8hewb1zGFlnDplUYpzLNRRkcTd6S8M=,tag:tH0cWA+fwcnQDPR4q4Rlwg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:taJAFSc9DrnaJMGGrFV3STuQDlNOMRbH,iv:DoZknOAFjkL1VzEo2qZ8eOB55XgCLtqDMN+BirZ6xn0=,tag:a8TGYBNRKM/+nQhJ1eC1SA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Hd7tRxmbXWkYto6bDFoc7kB1kragF/Yf9hjPQ4NapH+eHBlz,iv:D/Rmh+bPgKGmrpeaJQHz7iAx9TtNN26RgGLI4QnxyCM=,tag:8i9AV5bcyckhFtJPRBfzcg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NWyphubyUC7pT8pKyMwUG4Tjteb+PVcHNA==,iv:PjGLANOWKsxsHggnl5eskdmJL3RLO6du770KQjOhpK8=,tag:Gqct/WFPUfU6PLOE7GRnYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T07:56:47Z"
    mac: ENC[AES256_GCM,data:IhUEHgWfbyWkI3qgJSrTR6neuI7zWe9F1D8/dBJ6o02FSAZvtmr2pcONBZhQqVzheTwakSHZ7lAaaHp9DRBSLR6TB/Tx45OD50KRH028rqtODu7EORXRhPVesrYo9a0+si81ealr88n0YyJusu0v1VXJ2IAek74oWK/+YqtIwGQ=,iv:49Qk2BrcVg0TWe3YhKQcd6OhFS2db3IoIRQdv9kRS6k=,tag:gPAo7jGpTEJLwyzXPGH1Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
