apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:KiuqkXJIrpwYHEDnd3JsburA44tXGs1Wm6K5LnNyYwwYBTPBN4fU25GB9iwkV3ZNRcWLtYtBBjPLyi+ZKS0x4/VbYcvWsZgfqYvUUsANQcaSNCJMr4bfrwcYyvcphNKzP50rxGiMFBTPOwTuu5+WiiMYe7/PahHoHTB2RgECkKLdVQ==,iv:TDU603bdQjHNY4CsLsFSCJCaxgVLzX+D7BwlA6Dn0V4=,tag:pkoou2x3V0wh1ra8UTc/4w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:7ECtHzWwS5CjGQ==,iv:6M8GstaCzcSPeYsP+avChjWgTTl9H6GVBzk9If2SJ9I=,tag:agpUcL5WclpxTWQmbE16nQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:O43crb/T3kZCphB19c8sLA==,iv:YFQNiQgGhV547ozMSniul0KOgJ+9jQqJY1XLSgXt8GI=,tag:OiF+Pgl8SP2C5pffjkGlkg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NJB5SEtgoGFxtoGQv1OOs9n0yv3Ds83tjQ==,iv:UbHC1vzWOWmKGAK4Q8Xk2flGIbDap54zEE2dmg5gCEw=,tag:SM4tehXOSkgRzQiQiDDT8A==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:c1YE77W55cWKFTE1Gl5bkuPfrXbkLWmpzCKobBPR5vbNdY5/JFPVtgavxC1zacwhVege3aSpkY/u/pRXcGUAYw==,iv:LlMsrh6ayqw5wmhiuP1on47r9oUxqz16d/OVnIPOrhY=,tag:GoWPJXNo7Fzreh6xy6mGMQ==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:COhvXKCX6qb+ljmBFuzsRVoTDfO/RiZrSwxU3sYQgqOjVc8WV9m5cawN/hggIAVfzlFAcQbnZzd3ZIQAwT5Ajy91j5b8teBlpOvy5ZJIcltWbt/w0IxTdmvT8gE59RRFh3BizhO6NtGmx3AwRynuXHnn3JASEfq5w8XaHQYXuoM=,iv:cy06I4p5rcdm6P9KvRlA+Izij9M134Q8ovt2DoRTuY0=,tag:Onr6MHoG5AiLNnS5pRIEqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T17:19:18Z"
    mac: ENC[AES256_GCM,data:k14x03qSvJTGuCCRUBEuy07V1Y5yR5NXphpaUn4MUQPeBgzK/g3vbmNIkzcDkR5uVu6h5AkMWE5t+X9/1EyI45WU2mn2nZ7U1YVfwogGY/XujAeDIqtfJfWrDopzFfSlNxPIyYg25mtIsmF/4NvzugVvRtl6csWBazuMkhBY4vc=,iv:d12e6I8tLzDVKHEbrrt8FVmyOtg8OXK4Ef8QzCeXU1E=,tag:9Stb/71P/hHo2pbiaY2vsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:vSwVyMSbZpplsn6SPv3DNrczcZNGsCf7AQ==,iv:IwdVH46BTu9nEKRi1ocrVDwZeEuvAjOIXmAPlCaMjQM=,tag:OLuUpILobU6gTT1cGhBCEw==,type:str]
    password: ENC[AES256_GCM,data:yu5R9vIv2FMgeRBQ39ppfnr5iSIzTin39A==,iv:85NpEwbUVANa8A2bbcubOicntm3XSIFSM0J5gZlUohI=,tag:/MQq+NPJs8LjdDITgv5h8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T17:19:18Z"
    mac: ENC[AES256_GCM,data:k14x03qSvJTGuCCRUBEuy07V1Y5yR5NXphpaUn4MUQPeBgzK/g3vbmNIkzcDkR5uVu6h5AkMWE5t+X9/1EyI45WU2mn2nZ7U1YVfwogGY/XujAeDIqtfJfWrDopzFfSlNxPIyYg25mtIsmF/4NvzugVvRtl6csWBazuMkhBY4vc=,iv:d12e6I8tLzDVKHEbrrt8FVmyOtg8OXK4Ef8QzCeXU1E=,tag:9Stb/71P/hHo2pbiaY2vsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
