apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
stringData:
    #ENC[AES256_GCM,data:1ioCFg==,iv:TCnd/jgTpSd48CIkB7in9ICkEJK6WsKWTyaxpUdgWYQ=,tag:Qafw6SvN+27nx08ZP1C8tQ==,type:comment]
    RADARR_API_KEY: null
    SONARR_API_KEY: null
    #ENC[AES256_GCM,data:3d0ak7dgB9Dh,iv:kN8SHPY1Ay2qklw0IcgOnzYk3yIzaolBczaB4XHXtRs=,tag:9KM6Ni+pEs0gjUVwC7qYhQ==,type:comment]
    PUSHOVER_URL: ENC[AES256_GCM,data:/KmozouBLRWjWrvfbS8riXzlaRmrzKVdpdGwfGfTIgngtid5kFDqXORBpVFMJu9oYUbW6JQvz78cL88=,iv:HQSDi8gmAehRvzUR2GFA/PYYDGqRfkLQXY56C0kIUMc=,tag:CerpvtcFG5kpuhGMxyJFog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T16:47:55Z"
    mac: ENC[AES256_GCM,data:xaKWP+x0ELmXBrYBDUF4opUgpql1V4r52X/7sq0eXd+iyeOooctrajYN41SRZtfg2AKljJjucf5BVWxapPJrR0+FOwZO3v0lJClXaWM4uzxikJIQPZogaHyUVj8QY4c3Md3KlwRs9mXP7zPgzWFhmkgTwsc0JGz5NwJu0/H4mZk=,iv:/utjT0nzpqrrmI0ThEw7em9qieFnPFgiTjAA55ofqEY=,tag:UPvNMRDhhhqpcrEZEFMV0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
