apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:km0NQvRJj85FEoKoVUHpJzc=,iv:2Aq5earrrVilpo2jjA+3VUbej1B5f9AzJ6OvwzTvY+c=,tag:PhA+0gQ2ZCWip18kOz2JPQ==,type:str]
    admin-password: ENC[AES256_GCM,data:JsWPXfOuEkVre/HI14WvuHafxcsu8TfW7FoIBy6Z,iv:bBzaMWfhSGfbj9LvMzrLqaGVcra3IfQihKztO4xe7pg=,tag:/4dxyWJdCW2xKqtRBMM9QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T19:09:38Z"
    mac: ENC[AES256_GCM,data:EXPssiwwm0arZwLIZ6bX/iKZNS6FmXrHVix8CjU6r21/MfTSXhD8kDZ9kAlUJRJhHsJdr4qY0Nd9eSdFp7AEnaYUng24tvIcjfNWkdL5BNjY5UJrUSvX8hEf7zEuYCVrOJx7m0kCbhEKs+Vwx8zy5z+wuVdLBWw7BHCLTIPAfWA=,iv:G4B6x6mzrqnV0z5GhDhMwQ/v5SEyhi1x9Zvl/1juKDo=,tag:kqjow7RxmWDZbpBlWMU0qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
