---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plausible

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5

  values:
    controllers:
      plausible:

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17.4"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: plausible-init-db

          geoip:
            image:
              repository: ghcr.io/maxmind/geoipupdate
              tag: v7.1.0@sha256:e596817580fb150490f9897390a5a8b52bcfb8b9bb69354ae9bdfd47a949d84e
              pullPolicy: IfNotPresent
            restartPolicy: Always

            env:
              GEOIPUPDATE_FREQUENCY: "8"
              GEOIPUPDATE_PRESERVE_FILE_TIMES: "1"
              GEOIPUPDATE_EDITION_IDS: GeoLite2-City

            envFrom:
              - secretRef:
                  name: plausible-secret

            securityContext:
              readOnlyRootFilesystem: true

            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [ls, /usr/share/GeoIP/GeoLite2-City.mmdb]
                  periodSeconds: 5

        containers:
          app:
            image:
              repository: ghcr.io/plausible/community-edition
              tag: v3.0.1@sha256:14c1afde21d6555a41fad0e8db9445d835f5722238f7d58bbc4dc8c76d7aa499
              pullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - |
                set -eux
                /entrypoint.sh db createdb
                /entrypoint.sh db migrate
                exec /entrypoint.sh run

            env:
              TZ: ${CLUSTER_TIMEZONE}
              DISABLE_REGISTRATION: invite_only
              IP_GEOLOCATION_DB: /usr/share/GeoIP/GeoLite2-City.mmdb

            envFrom:
              - secretRef:
                  name: plausible-secret

            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true

            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups: [10000]

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000

    persistence:
      tmp:
        enabled: true
        type: emptyDir
      geoip:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/GeoIP
