apiVersion: v1
kind: Secret
metadata:
    name: invidious-secret
stringData:
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:6cdQKLOxAgcT/ZF7TY/N/rAdt8zuKNGP0ejED4j+k/DgFz30Bye8b4qLKJGY64E1Bcx/zNJYS5nvtuRn3hoLx/BOk3SldJ7fzg1caiFyepx0HywoG6zud5qAO/8rwdwkg6KrazkgIDWButQ0ZhCfj9VYzm4+e3ptyRcwH1RSigct2V6wWGlWHnGMj5wGOt3mGdf8yMs106G9Jic/ZqaSvTu5MTIGsFrSQC0KPh83nQNV7nT1Yb+EVD9IwN8lIWQnRsP6I+k0ZP6RZ+GhNJxhxRlr/mnblnz8jgnT8SLxQ1+BIr5pq8PhLvJPPpvg7Cc=,iv:FicnafADxqRlC6kf+8IhygNQdCUMKGbnBX99Z/7971Y=,tag:nDrtBn9Uv5C1EpnQSCiInA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T08:30:53Z"
    mac: ENC[AES256_GCM,data:PoEO9RSzDun/+eU82Y21aNy4BhGw03j45OxUK3OEbOSz3F1gZLPJN0nu7URZBaPv0Ak8aFxbQuxLQeT/ZWge6aQfJIfa08n03VzBiOXmZJST0xMcv2si2z1BGcyzSD9CCYrTU1IExSrHcpUV/OoSbAYzoA3VXWPJwqXwx0Bp370=,iv:QCHpCczh7DD8q+XO5AJlpTxy7RaYQ2dksx6aatdwA9o=,tag:/TlK5VnKi2B2y/epJjI+Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: invidious-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8NSoZfLqbX+vYGdV,iv:0ZRFbUgEQ5T/guBhFHFKa0YZz7myExukYF50XFhi7ug=,tag:nQ4v/KlT4m7r6BEnrfYNXg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wSVnSoOvaYJvxXivvZho9eY9brc11MTadVZHPrTACmz8fEpZlNdea6qbFQ9byzc4/SXlewtP1N4=,iv:Cud7mJrWg8o7c56e4eZeM82/0FZpBlZPcAJfjSIFWW0=,tag:+p9wJOsfFG96DR2+efhL9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:rCd4Y7o3YUeeLT7OG04vh/ZXNUs=,iv:UGxXqfl3y/B/Jmc15zU72XKJ96WtZU2sa4cjQvx7JME=,tag:5tZ3vvQqG3QjY6lpFrHfzA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:rwuMunoVfXg8NIDyIqBK2BI83L5a+QC2zOMjf3MyTd8=,iv:eBN5rNMMGwZ5q49yhtNpBmSwKPgwJ8Kko5/uvVeUxOc=,tag:NHge0YhdYam7RGU87bZ/Yw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T08:30:53Z"
    mac: ENC[AES256_GCM,data:PoEO9RSzDun/+eU82Y21aNy4BhGw03j45OxUK3OEbOSz3F1gZLPJN0nu7URZBaPv0Ak8aFxbQuxLQeT/ZWge6aQfJIfa08n03VzBiOXmZJST0xMcv2si2z1BGcyzSD9CCYrTU1IExSrHcpUV/OoSbAYzoA3VXWPJwqXwx0Bp370=,iv:QCHpCczh7DD8q+XO5AJlpTxy7RaYQ2dksx6aatdwA9o=,tag:/TlK5VnKi2B2y/epJjI+Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
