---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 5
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      bazarr:
        replicas: 1

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.6"
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: bazarr-init-db

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.4.3@sha256:4fab44133c913d3988d7b8b38b22170117db128201eb7e2ca99ca63c56dd9d08

            env:
              TZ: "${TIMEZONE}"

            envFrom:
              - secretRef:
                  name: paperless-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 6767
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            resources:
              requests:
                cpu: 23m
                memory: 300Mi
              limits:
                memory: 500Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      add-ons:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /add-ons
      video:
        enabled: true
        type: nfs
        server: 192.168.9.10
        path: /var/mnt/vol1/video
        globalMounts:
          - path: /mnt/storage/video
      scripts:
        enabled: true
        type: configMap
        name: bazarr-scripts # overriden by kustomizeconfig
        defaultMode: 0775
        globalMounts:
          - path: /scripts
