apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
stringData:
    #ENC[AES256_GCM,data:kH5oTQ==,iv:oiKh+ux4mfxysCAS+gC/xlSBU2JK5Aw2g5cYkSXPEIk=,tag:EKyO+99FKEPA6Uxn1a396Q==,type:comment]
    BAZARR__API_KEY: ENC[AES256_GCM,data:Go7O/cYbOLSR7TM8LIS5Fd/kSFzmOky0IKzrZEmt6Hf7Ffos,iv:tJ5FctNdR7dFEjtHxTMMc0ULib1ZtH0hm1LlEQFWj+4=,tag:vMb5n86AC2kqIsJkIEYldA==,type:str]
    POSTGRES_ENABLED: ENC[AES256_GCM,data:BGP2ig==,iv:hROOb5XafhYyFuOyOdDHo4r0MskCGYw/4Tt10RyvdDY=,tag:z1ZJ6WN3O5qzUHy9jOtrBw==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:3iMkv7Ou,iv:60dtkBwdndmeEmLnGjB19b0vugylp8kl47YRIHVGKlA=,tag:Nw6NJle6bbM36r3pFzdcYA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:DQfSfLFJM5riH+Yo6QJhDNFzdCUN,iv:FV4D7FdT59iYYb+8YOCOS8+vtIRsn/413CIk8aqqh84=,tag:GlVO+hDoKpw7FDQcVLIChg==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:p3O81w==,iv:B6c4PwaVFEgxsYKTAubKrQuZJEwGW/MdoZxe/DzYBP0=,tag:3bfIjQHWIQQ9cBOpVBWkPg==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:uJ9oXnV7jB+QOZGa,iv:wajzONhLBhHxNcvOB6AFhNND1YBCIT9SwAtKuFqb1sE=,tag:ErpHsHGiAqixOQdug27cVw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mlN+7wWd201tx0zdL8dEaufKSkWDJ63m,iv:doHT3OAh8BJdYg3zZZQwsVSQvQ8fWfGkZOK6h0nl7wU=,tag:n+mrEcROjQsIQUiZZtCP7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T14:34:57Z"
    mac: ENC[AES256_GCM,data:fbodrEz/BFR7eR7W5dkbymZOlu7t5aZVLr+GUG/CN78Yui58zeum6HWPpR5FcMeJ4AMnTowjsioS+4VEdj6w1FU9vpKmo2iHn+s3U1bzBw+1ymQcpOzewPNAOfUvkXM1kV2slk79XZpNE8PvpPKS7MsIVwEedqHfCnZ1jVW3cb0=,iv:/kNgxhE96a8AUAWZxT0rCwqwZkoixqoHs+39UF3ClEs=,tag:McNb3NJpzTpPfeCyRgHOrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bazarr-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:lbCQ92Ylt74=,iv:vUSHoZaluut2/ItEScZQCy0iorg8L3lGSU5WFdSdH+g=,tag:EaUtAI5Dq69z0uRA1+kdyQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/YJ5lygeszrIvvnGD1Vxbi1SuhHE460WhGPp1Lih5LtPs3hE152rskoaLok6mr0ZdBfleEJ04Zo=,iv:vI6PY/gBqdTxUOQfFrB4CH4Q9VBFMVlIUEhFFHCNfls=,tag:XLl/+TXVGMAXQb4sqAAD2Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:RTvtx+U8ao76BkSCcSn4bg==,iv:lsLIVT6SzBkWkuAY00PsmXyXKlRuYZ/b6iBQFZml1q4=,tag:3bSQ0rApEz5TysHmuAGEOQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KYbyn7/TuyGAQ09c3bYs3lLa4fbYdmq9MSMhfdmzMzI=,iv:NdBTJGGaaDCXg7Z8OwqxTVXc88wWqYuexsxfPy6zpP0=,tag:S0J3MfrSv9b+bHDBnvt7bw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T14:34:57Z"
    mac: ENC[AES256_GCM,data:fbodrEz/BFR7eR7W5dkbymZOlu7t5aZVLr+GUG/CN78Yui58zeum6HWPpR5FcMeJ4AMnTowjsioS+4VEdj6w1FU9vpKmo2iHn+s3U1bzBw+1ymQcpOzewPNAOfUvkXM1kV2slk79XZpNE8PvpPKS7MsIVwEedqHfCnZ1jVW3cb0=,iv:/kNgxhE96a8AUAWZxT0rCwqwZkoixqoHs+39UF3ClEs=,tag:McNb3NJpzTpPfeCyRgHOrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
