apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:7bxLNoyvccbFvx951Xn4Zsry6jTCSJsbYX1bWKae,iv:fMtgNGfZ+N39zx5addzeDGv5uKqJM+22bNvByKzNdVg=,tag:+gmSUN2KvURGBzSqDEsYtA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:ulYbKTXxhiVEWqqVAx9/Z+11DwvgoY1XvRZHqIxO,iv:jo8ULx0OyJ9BNnVX1sFjazEwZoBLy6vMWpXxa1/RTzg=,tag:alm840QpAZkcN0jovJ+UGg==,type:str]
    GATUS_DOMIAN: ENC[AES256_GCM,data:SwTmceafcjLB3aHbwBFJ6aZ1,iv:oprZhTccxleldDdsuiTQbeEO+kFgSMoYpEg+vCWvG4g=,tag:A948yWyyCMzFD7CjG4lSDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T16:01:09Z"
    mac: ENC[AES256_GCM,data:XB5gizk4NbEOCggelnTUF+Wv1scIFzHHS8FSoQzzV2IwMC433X+EoqDH1aIBamRe+9CYMEeNd8jnywAHRwvYQN0oSk0shESPwsPP5D0bpsRRJJEZ+OVwI61ooGka4Z/Pe8k+MvQVGJ3JXaOMJDJDe5XCZwlxcxF72947RzCNgJk=,iv:XQl+QysO6komip1SIXhshprpGvg9ChmboYCrABL00d8=,tag:fE+0C1oOUJ1rcLgOSSmjQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XgEcXOczOW8=,iv:g2wkGQ5c+WtaOuV4jfKAKyvTVlgQEibSPrq5fXMkbOs=,tag:/1PMvLxYEdlNxeh9VxPf0w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/I493OhDuhz95Cb2/T4H0ZPJyJudZGomt34unbD2pf0CP9vCXYC/A/8o++1U9uINn/IwTpVh9Os=,iv:zjAqJZ81+jfTacA5R7pS/MEPmYPHnAxx2Ktv+n6oDlM=,tag:CUF2tOP5QiEEZgBry60sCg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:rH0YnNf9Bvjvh5uaubeMNg==,iv:gFuWlg5or1RXNnqVjFQHD30ynwiahLnOUlEQQ+A79Yc=,tag:euUwEV2Z/K0YLwm6apDahw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:uJu2lMi9S6acnt09KpqLonjgxHitDE2vtMcRlX+wvc49oYGW9fCnACYJYeQ=,iv:j2gmlYO1PYuZKMBJM2dR3XQ3aHQCi3gXM08oU7DxlxM=,tag:f31EiOX5FKQU9nSXMLfJcA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RDxgqjN47U5KzrHbS5ODbq5sbzxIn1xgUg==,iv:0QP6LkhzCG8cc7b7bzSKIHzqm74YuxW4Zb+fzjQMZF0=,tag:sWbdFdr7VlarFxCyUv+Z6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T16:01:09Z"
    mac: ENC[AES256_GCM,data:XB5gizk4NbEOCggelnTUF+Wv1scIFzHHS8FSoQzzV2IwMC433X+EoqDH1aIBamRe+9CYMEeNd8jnywAHRwvYQN0oSk0shESPwsPP5D0bpsRRJJEZ+OVwI61ooGka4Z/Pe8k+MvQVGJ3JXaOMJDJDe5XCZwlxcxF72947RzCNgJk=,iv:XQl+QysO6komip1SIXhshprpGvg9ChmboYCrABL00d8=,tag:fE+0C1oOUJ1rcLgOSSmjQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
