apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    #ENC[AES256_GCM,data:rcCvtg==,iv:0xxi0VAhY1zNPLeBDYX2RghfQDkCm3o1YLrshgwkmG8=,tag:P8qYLQpdPczTiXTrfVBz/Q==,type:comment]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:e773um9YPE41CKCfxvnaAesmjpg04qfbbOdMe2Nj/0l712Ox,iv:ZhMEOH4H8WrfGhHs0Sl6PUWLI0bUqz0nKXeZIcb8FcI=,tag:dmS2olS7Eq5kLvG2FQedDA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:96fTJ0MbUvx2Ilf8BQpviOngwwRx,iv:NhoQ06Luw2qtu2zBi+IN5qfCQBCgAJ5NbOoyJU+aCvw=,tag:0Ch8dES8SNMQ6RXRzU+2hg==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:X4wBHQ==,iv:5yr2oVXtzvEoOFulj9Y7TJ2drOweXz7eXTtM5jeVOFA=,tag:ejhNN/j2EQR1bEvQCNfglg==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:y5UtQ7RabMkwH0hgx8A=,iv:4RIwnQwn0h5ruvj6YY9SPBt5YGOKAOlTJ7S61brBKc8=,tag:vuIc5s6J8H2AMKkxgik3XA==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:RCM9AxBjVzRINUGC1fRBQv0LBhVAogwa,iv:yU26o4DXBpyVp0lCjF4561I7OEFAcDSBX5m5HghMzxM=,tag:Aslu7zKSKjn2AL5eb03NEQ==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:prJSfYO9wk4=,iv:kpI/2JhezIbFfaIwvNUJks9N8/4cbEdGVamNoM8cH1Y=,tag:d7Bf6DC3XZUHskcy5X8UNg==,type:str]
    #ENC[AES256_GCM,data:0BZc3LNANJO6,iv:sZvus4HVMzrNREyi2IdV8CitpC+xyJrkoNjSKiyFUN8=,tag:nGQYy57Xtr0BHz9PjEBDLA==,type:comment]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:terplhgErHPWxoaop+eQEBBR2yCy69XAJSnHoqJl,iv:4jWrfwtMLcCC6H14s0ahoxE3xIHef8ljvmHwhIJellI=,tag:+5Dsic6nN8Qmjc3CG92OYQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:vd2b7MVFLiE/11iIG6E/70Y/lwI=,iv:yC9I3VV+WCjGm/b3tDhJd7WGaIfCy0Ltd17qOktSXZg=,tag:zvbG4SpSpttpDEkYN7E3AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:01:53Z"
    mac: ENC[AES256_GCM,data:mo+eTSs6eQEJ9pvTAaTVgdlp1gAegNdpYNPlxurczABHu/jI81kb7zTYWG7BtERRm8FNkLkpz62iN3BsvM+K1siDFv4ze9pPnkEi0ViBfu09o1Dj6ewaVbX+ouAo437dWe6VXYpsKJv7k/27MJ5a8NBxwher/RyXHhHCnyV2yGg=,iv:Hy5yoMJ3rIUN2GP48SVXTI0fY1Y+ThDOo17egQbbVV0=,tag:rSXHPMQXJSdZEn03vCPPhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:pK/yx7EnUIU=,iv:CSXl9DTS8QYOD7Hjsn7xGDsSJW+Rfn5U0lOiZEY5nQo=,tag:9qCo7Pruu1GqO4L9gAOLxw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:O03YETQJBpHnseQR1YxmwAlfcpeVy02u5Stpq8wZlijCemt2CS9FpX2GvShLWkXKCljFwncOgAs=,iv:scb5mSzfuvaFWdwR4sQOg3DA2p6UVNuXmJPsoAc5gtw=,tag:IWFV4SiLFW7p+5eeYU+6wg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qMvszKf6Cw5bu7cDSq5oKw==,iv:MFtCUoEDmW/PEU/Q7g+zkBz0byLFd0rgwI5GTY+J5t8=,tag:h31B/e53csj0BmqcrTIXKQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:NYQeFO6igwKo1/ZcV1++0o6MtMIS7/GVP+ILDFpiqCs=,iv:hsBeVAj75S9Jppu3QrZWTbFT95tFfHMO6Tvo3PZ2EfM=,tag:M1B9yFUts1PkBfk8J7derw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:01:53Z"
    mac: ENC[AES256_GCM,data:mo+eTSs6eQEJ9pvTAaTVgdlp1gAegNdpYNPlxurczABHu/jI81kb7zTYWG7BtERRm8FNkLkpz62iN3BsvM+K1siDFv4ze9pPnkEi0ViBfu09o1Dj6ewaVbX+ouAo437dWe6VXYpsKJv7k/27MJ5a8NBxwher/RyXHhHCnyV2yGg=,iv:Hy5yoMJ3rIUN2GP48SVXTI0fY1Y+ThDOo17egQbbVV0=,tag:rSXHPMQXJSdZEn03vCPPhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
