---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.8
        env:
          - name: INIT_POSTGRES_HOST
            value: ${POSTGRES_HOST}
          - name: INIT_POSTGRES_DBNAME
            value: *app
          - name: INIT_POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: INIT_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: vikunja-secret
                key: VIKUNJA_DATABASE_USER
          - name: INIT_POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: vikunja-secret
                key: VIKUNJA_DATABASE_PASSWORD
