---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vikunja
  namespace: flux-system
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/services/vikunja/app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: rook-ceph-cluster
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: kubernetes-prod
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vikunja
      namespace: vikunja
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
