apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jr23,iv:owHOJiDz2yfmU54jFEBuDzFMQgeCfQ+WGpMbvcdHMWo=,tag:x1sMZbmqnzp1Moik9e5KJw==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:VfKLp7ej/ygFYci2NyDEHD97DJhE7DbXqKMdH2DwCvo=,iv:Z6wJwKSdxXmYJ+YxlPk7GItzbU2ekciUbc8wL8Ktzrs=,tag:WZZJrAdiBOc9Yi62YJC68Q==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:EyQsBQw=,iv:5QXk9NGoIfga40JGvSnocqv35A52zYUTEHLUgOZhzKo=,tag:QNYM7Ytmi//p8vTKvU5Pzg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:zEHKPA==,iv:MVDT4PtBLLqFWxpeI8xVo5D/ulu+5ka8XA+azQ8mgr0=,tag:UvCBCJZv0PkZpfj+B+8YbA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:lkK1RDiN,iv:Tx29FuF4soZgu7BhzKzHrq8b2tmWe9iOYe4axPHF/AY=,tag:T2L/7s+X7upW0apactMXPQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:SE0gc+d8bTeDSVezyy7rMg4t2g==,iv:l6DHz4AACxz+bmBkX6VqA4qYOYMDYKAB7VfKXQQmFfc=,tag:AruTJ8gx9UvqcnAu6/ZOWA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:y+ZcRXiA5QhxRKsT/jMYph4SFCg8OVGYZQ==,iv:T8uWNb7ztic1iVWhkCg/ABWN3Vi7xA0gokxj2bCYyBw=,tag:Zy/F7S6eUYhEmQcmCvRMiA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:kLSR7q2nz5gVGV3G4w==,iv:nkYyl8sbaCp30ExzlogBJpML/Lk0gw27V+9g0pfOcFs=,tag:s8tkIOBqX1RIzR8IXhVzHg==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:IvJx,iv:JZCAO20fhmvsFpGa29hhbjaU8Q37MYJ/Jbbz4FikHLc=,tag:KeTO3TAgD//Lz6GoCMiG/g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:SmgDXt6TrFfHq+KG0Paaq8hWpYxqgNnhatWzrQ==,iv:1dHEdJ5s3IFKURLmK62Pg+6zdqjUljDoIM2o7JHUJ44=,tag:zrzalHs4IeRn+SSgr5ag2w==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:S3vfTLqs,iv:2oAcAZAXOZOz8zOF6KrJ/lVakZ922aJaVv83vaY8BVk=,tag:3wC+a6CVz6EeZh0SUxxSXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T06:52:00Z"
    mac: ENC[AES256_GCM,data:FXaAde6/wLSM65dt2XBy2Gpcv8owZGskQgegQpC1gZlvt68PLPPnCS2h/HxTZgyEDdo8NiZDFb28ViWL1/b7x4eyd0hFLwdqV/GYuO5U51OGaZAcLrdqeFfGZsrH0cSJEQa9lAiWHaV71IPv34APd+Uu/Dez/jc6VtjFrH+61CQ=,iv:SfL4eDMDiNPe2ZPfcfCqCH0sCu+hZ5UDllML/gXtcDM=,tag:yZYA5byi4Q5SBsXKEHnkvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: monica-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5MQnZ//RV5Q=,iv:g3gZECVvkALcRgYCPtWUeCUdYkjOVMpG1HAcTcSHPf4=,tag:IfNLWuPpdNdK+56NCAdJ1g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:m8mi4YJ9+VYzlT3sr5+syKkOqrEIcPsKjQbLCe7V/7h0aiOXSJgctcqvxLKuebfj8qPwlt1l+2o=,iv:HI1QE6Qz07K1+Tl0kL4wJO5HXUsfut65ytRCrMN3Ezc=,tag:b3uRkgUEPD14ExginJUCdg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:wKEVQaPMo7QqNiGa3ni5d1pc6I4=,iv:I+/wsb1qM6Kfy4PSA5rPHIZK3biLkGmBjq8y0iyxIXE=,tag:bTeXU8RJRcCy3wOdCIh5bA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Pcc8cxQU6MjVlxDAiyi5vbU5QkuB2itXmLTvm5PeDMkppCwL,iv:Tdnm1C5E5ksEsaN+gwP/wdqc/yxW82ubWnrEgYzoDIQ=,tag:OzP9K3aWBGxxxaQNamH6QQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NI/TN/UW9/cOeOy1gvr1nqyMPuIY7B40Cg==,iv:kepcpU2G5MYVbcDG9U0V6xKYI+QW2wu5hSLbT8R6tJk=,tag:gm7h2zlh6NU4ejQtTG/e/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T06:52:00Z"
    mac: ENC[AES256_GCM,data:FXaAde6/wLSM65dt2XBy2Gpcv8owZGskQgegQpC1gZlvt68PLPPnCS2h/HxTZgyEDdo8NiZDFb28ViWL1/b7x4eyd0hFLwdqV/GYuO5U51OGaZAcLrdqeFfGZsrH0cSJEQa9lAiWHaV71IPv34APd+Uu/Dez/jc6VtjFrH+61CQ=,iv:SfL4eDMDiNPe2ZPfcfCqCH0sCu+hZ5UDllML/gXtcDM=,tag:yZYA5byi4Q5SBsXKEHnkvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
