apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jr23,iv:owHOJiDz2yfmU54jFEBuDzFMQgeCfQ+WGpMbvcdHMWo=,tag:x1sMZbmqnzp1Moik9e5KJw==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:VfKLp7ej/ygFYci2NyDEHD97DJhE7DbXqKMdH2DwCvo=,iv:Z6wJwKSdxXmYJ+YxlPk7GItzbU2ekciUbc8wL8Ktzrs=,tag:WZZJrAdiBOc9Yi62YJC68Q==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:X+KLXOk=,iv:uMPJVMhdAsl0WO9+UE1zEbbAtJCFVLW4fLm7zW9Ekb0=,tag:bJ9OW7X+quloE4igxfgnLA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:mQS8Eg==,iv:9HgWEbEo3a5q5V1iWXGBwBBmOTct0YKa/B7ULL8jB2I=,tag:kG1TOMx7C3HlEZoECgWmDA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:lkK1RDiN,iv:Tx29FuF4soZgu7BhzKzHrq8b2tmWe9iOYe4axPHF/AY=,tag:T2L/7s+X7upW0apactMXPQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:q1JsjSmeg4dzMO8ycs2Qd/sP5oYkluAE8YOAz88xF/VACyK6DQk=,iv:Uwh89PMaRp3ctD6c6LVpcWCY8DwSCi5G0x/chn8kxQw=,tag:uWFQhLGw2ekeXZFiZUJz4Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:uzJC23T58Haxf0mi27IozvKegjf/,iv:1ie83/4tFgBNMMqhPxVSDN4hAdrODAeViJQhmehBBEQ=,tag:lMbpcqcra60DorwE/mbHhw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:M8vHmFLtsaoztoIJmW2WZHPtZCwV,iv:7iXmi947vsrPaC582OprbjHkPgUS/35vxvWHdlsBg5Q=,tag:7h1DU79hyLlZEGzr0ykOwQ==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:IvJx,iv:JZCAO20fhmvsFpGa29hhbjaU8Q37MYJ/Jbbz4FikHLc=,tag:KeTO3TAgD//Lz6GoCMiG/g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:SmgDXt6TrFfHq+KG0Paaq8hWpYxqgNnhatWzrQ==,iv:1dHEdJ5s3IFKURLmK62Pg+6zdqjUljDoIM2o7JHUJ44=,tag:zrzalHs4IeRn+SSgr5ag2w==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:S3vfTLqs,iv:2oAcAZAXOZOz8zOF6KrJ/lVakZ922aJaVv83vaY8BVk=,tag:3wC+a6CVz6EeZh0SUxxSXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T18:53:24Z"
    mac: ENC[AES256_GCM,data:P5UtS/HZShG1LEFVHaJGW+jTIBzpmziydRXKrkcXUGdAZZitB+AZIjuZui/GK4oYTyFvxLG8AXefyipaXsurE00IwbABbwdIHmKd6GBSEL4n28d0tFoYpu08/LOeb5/vqOzlmuPilB0LQYHsgztzkXY7PPL7UjE5BhWd86BzzOU=,iv:8f47Ff3bctr3NssQiNKrt89mioZ7N9B6S6tKu/xLk1I=,tag:rKSEgzFBWmQKOdjqlTBXlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
