apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jr23,iv:owHOJiDz2yfmU54jFEBuDzFMQgeCfQ+WGpMbvcdHMWo=,tag:x1sMZbmqnzp1Moik9e5KJw==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:VfKLp7ej/ygFYci2NyDEHD97DJhE7DbXqKMdH2DwCvo=,iv:Z6wJwKSdxXmYJ+YxlPk7GItzbU2ekciUbc8wL8Ktzrs=,tag:WZZJrAdiBOc9Yi62YJC68Q==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:lkK1RDiN,iv:Tx29FuF4soZgu7BhzKzHrq8b2tmWe9iOYe4axPHF/AY=,tag:T2L/7s+X7upW0apactMXPQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:XzRoClCboGxBtIO9NBLAAC/3pQVCq5/uq3LeCmSkk6Y1tSsNQsnwfsptAHbH/A==,iv:klJMPktwt5QDx2Cu6yeb2V+SJtK0mDF71A/1+xtfJ68=,tag:dV8Scy1bc7dmQayCDGbgSg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:uzJC23T58Haxf0mi27IozvKegjf/,iv:1ie83/4tFgBNMMqhPxVSDN4hAdrODAeViJQhmehBBEQ=,tag:lMbpcqcra60DorwE/mbHhw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:M8vHmFLtsaoztoIJmW2WZHPtZCwV,iv:7iXmi947vsrPaC582OprbjHkPgUS/35vxvWHdlsBg5Q=,tag:7h1DU79hyLlZEGzr0ykOwQ==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:IvJx,iv:JZCAO20fhmvsFpGa29hhbjaU8Q37MYJ/Jbbz4FikHLc=,tag:KeTO3TAgD//Lz6GoCMiG/g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:SmgDXt6TrFfHq+KG0Paaq8hWpYxqgNnhatWzrQ==,iv:1dHEdJ5s3IFKURLmK62Pg+6zdqjUljDoIM2o7JHUJ44=,tag:zrzalHs4IeRn+SSgr5ag2w==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:S3vfTLqs,iv:2oAcAZAXOZOz8zOF6KrJ/lVakZ922aJaVv83vaY8BVk=,tag:3wC+a6CVz6EeZh0SUxxSXQ==,type:str]
    #ENC[AES256_GCM,data:0FTsdVrm278tqL7RkRrA,iv:ivTMP7xTFsQB4fp0akhwhOTbtcumJuX4FiF0xHWSaCU=,tag:7q0MjWDWqoBB0ZgC6FxeSg==,type:comment]
    #ENC[AES256_GCM,data:ZomKSTIIEqvKx4CQ9MeA,iv:gDNeq7YQXxq5Fuyfygxaq/cFd2t6dFIdehaGft45THM=,tag:zI3e+plLE9FgDje+7cgEmw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jN60QDd91yBwkSnwVm4kkUGXQCo=,iv:tW+i3UU8VBlzr3SilfzF0UlmXyR+fzPRyeeVcuxy9Jw=,tag:4/7OQrh9AU9O8DAgyNNdBg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6kux1psK1FrDpT3/UiCgvxJD7cfB4ZmNxqXBgkX8ybY1EapVOmtewg==,iv:Btr+9ato5gbU54vQNT6gOIdiLetu31yMbkbJ/F5nhnI=,tag:4cuV25At8+PAEqqfz4MGAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T22:56:56Z"
    mac: ENC[AES256_GCM,data:xTP9XBYFCMIclSJWP0fYKNvay9aZA1k46aN8ml4fKVdfU8wTK+wi0bKBrR1vJ9QxHPDmUMEypS/3gmUeQyNi6SOOhwdRmdWHu/z8ZK2Pin0k+QiWlXz6vYCcEZVq2EaNlrWM6oOJApup5oanxHYK3TIiwZ/YESk6nsGe8Cwb7v0=,iv:jm+3S/g7b2+8ZDcMocvKvuu1VV3oYlyuSzyIxs6E6E4=,tag:ICrpmrT20uLC8REdlI0QyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
