apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jr23,iv:owHOJiDz2yfmU54jFEBuDzFMQgeCfQ+WGpMbvcdHMWo=,tag:x1sMZbmqnzp1Moik9e5KJw==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:uzb5i1BRbJN+w/UrNS4qf3aRYYW1Ithl5/EUaWUT1SWb+/SwL9L2EWdxrCA=,iv:rSwAd5sOQuI6+LGWNqZK6yIEveG1UjfT3Kk3yyFKcBQ=,tag:1cjLZXYe2IPgJPTcciZjow==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:PgLSrhCdrn5F,iv:KrBOTlxYjeA8W1VraAxRKeqDuM8wxnx72c/NaTEzmMU=,tag:IqU1H2+UkQO15VjnVdjECg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:fscH8YuFZdaZiumWOUXqC0o+Twf47KU/nmOw1KZS79C4AzqbtEM=,iv:fOrJLShyu3m6WEV/A06Fhi9FC1eh2wfnVxHFp7RMqLg=,tag:sew5WhuKSvShS9QrFrop7A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:VThMQUhEryutBhROjeuW1z8dWR4uSGzFqQ==,iv:lli8LFWi8Rwx3yYX3r65DP4q/Y/i6BmtfeCHMunlNys=,tag:6GB1dB2M34zVUDxx8S0Dkw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:xRR3wDOdIt+eaU8xs3pBPQ0=,iv:uRl+T8skpakI2t24wOcMS4vGC37SdJsX9MrgsmZjzWY=,tag:ZSP3BYxuCFpDQAgSwbCf8A==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:IvJx,iv:JZCAO20fhmvsFpGa29hhbjaU8Q37MYJ/Jbbz4FikHLc=,tag:KeTO3TAgD//Lz6GoCMiG/g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:SmgDXt6TrFfHq+KG0Paaq8hWpYxqgNnhatWzrQ==,iv:1dHEdJ5s3IFKURLmK62Pg+6zdqjUljDoIM2o7JHUJ44=,tag:zrzalHs4IeRn+SSgr5ag2w==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:S3vfTLqs,iv:2oAcAZAXOZOz8zOF6KrJ/lVakZ922aJaVv83vaY8BVk=,tag:3wC+a6CVz6EeZh0SUxxSXQ==,type:str]
    #ENC[AES256_GCM,data:0FTsdVrm278tqL7RkRrA,iv:ivTMP7xTFsQB4fp0akhwhOTbtcumJuX4FiF0xHWSaCU=,tag:7q0MjWDWqoBB0ZgC6FxeSg==,type:comment]
    #ENC[AES256_GCM,data:ZomKSTIIEqvKx4CQ9MeA,iv:gDNeq7YQXxq5Fuyfygxaq/cFd2t6dFIdehaGft45THM=,tag:zI3e+plLE9FgDje+7cgEmw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jN60QDd91yBwkSnwVm4kkUGXQCo=,iv:tW+i3UU8VBlzr3SilfzF0UlmXyR+fzPRyeeVcuxy9Jw=,tag:4/7OQrh9AU9O8DAgyNNdBg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6kux1psK1FrDpT3/UiCgvxJD7cfB4ZmNxqXBgkX8ybY1EapVOmtewg==,iv:Btr+9ato5gbU54vQNT6gOIdiLetu31yMbkbJ/F5nhnI=,tag:4cuV25At8+PAEqqfz4MGAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T07:27:31Z"
    mac: ENC[AES256_GCM,data:HK5J1q7DpoZgIMFTOLc983ZMT/KGelCSSWNCbCzpi+E/b2hpjy6YHzg3ODSKgfWIzg3mGsAcvSnP8fS8V/7l0mSnlfykz3auK/WkZmh4EKTeqEGzT/4O2CV2WMS0CPLPScPSaEwNfoHucv3NqGqqQfTaoehyZPrggGJSS2UVVJg=,iv:mIqXnYU+lnlQlf3BhL1MCqxEJhp06yJRLceUpdTHQtc=,tag:cS9kCgFSPp1YfK9gZ1aHuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
