---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app firefly-iii
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.3
        env:
          - name: INIT_POSTGRES_HOST
            value: ${POSTGRES_HOST}
          - name: INIT_POSTGRES_DBNAME
            value: *app
          - name: INIT_POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: INIT_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: firefly-iii-secret
                key: DB_USERNAME
          - name: INIT_POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: firefly-iii-secret
                key: DB_PASSWORD
