apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:nSuc+MCdQG0=,iv:0NPZQXJnZyCA1d+ZKfnyg6KETNINirnK3k8mX9Qalk8=,tag:pKALSKBHvGcb1JQ9EDXWsQ==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:IOBdhiAfOS901bESYHpOSw==,iv:sT8qKWAv6syYYeP1PansW3ekARomDSHpG2/qkiODWxw=,tag:vw9bABmttoVQGYcH9541ew==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:tMg7UEBFQQ==,iv:cYIWmvLwjUmbJxuZkFtIYC5IbLJAd0/8fb8fjPMsHpA=,tag:KGxedKes0vMKBgBKQacpXQ==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:/IJ0GMFzH7kpuA==,iv:oTVrW0gb5fSHXIW9bDy/ORYv+3FmdHm/r4LtfNZJOCc=,tag:ypIxBci1K/BL19myksq15g==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:JtEYBHr58KFpwH+ishNgjRxvjxzb4XDpeg==,iv:4Shev8AGu7buW9OKuXsSE6gOkls7ODMzFqUHpQPiyoo=,tag:s5bwviKlnjkIDvK6lKF2xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T06:43:24Z"
    mac: ENC[AES256_GCM,data:f8Rb5yu2awTFbUIcKonSWfwcffsfLidLKATL1XPptN8oXTw34CH5jUndbqa6xhlqeP/A15/6IbaW6r154I+i/BIuPUsloaNhMG3wM7BHTKN8BOZAp1IcdwF2IP3g2xZIau8TOfmVTfWrqxsmRkbDn7KVgYOLhtcqzCcg2CarnTA=,iv:YhmgsxBNqgU5czm7pr6oftjb+Cep+ngP8IcjdDrY3Cs=,tag:mIBB4Q8CKQkNFe72wgm08Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:cKKKmrfimuDV1EB4rn8rwL2bIscM91/27w==,iv:5tViMveSx0DkOqUSW8hWHe/MnZrhuYmLH8SLcJ7l5Lw=,tag:TeIO/jptFVYh2UwATU2NGg==,type:str]
    password: ENC[AES256_GCM,data:EpnA/qYVOjUwVkebKsKlRam86NKuUux8ag==,iv:KR8NPcsQLHtIX9oqGaTGx9qT3fcUWNwAMHjMXrf0a3s=,tag:ifOpbxm+kHrtIz3B0Tly0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T06:43:24Z"
    mac: ENC[AES256_GCM,data:f8Rb5yu2awTFbUIcKonSWfwcffsfLidLKATL1XPptN8oXTw34CH5jUndbqa6xhlqeP/A15/6IbaW6r154I+i/BIuPUsloaNhMG3wM7BHTKN8BOZAp1IcdwF2IP3g2xZIau8TOfmVTfWrqxsmRkbDn7KVgYOLhtcqzCcg2CarnTA=,iv:YhmgsxBNqgU5czm7pr6oftjb+Cep+ngP8IcjdDrY3Cs=,tag:mIBB4Q8CKQkNFe72wgm08Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
