apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
stringData:
    VIKUNJA_DATABASE_TYPE: ENC[AES256_GCM,data:o3KJapXeFVI=,iv:MaERviyUt13P8D+w0Oe3D0L+NXkXgthLC96UcXPhULs=,tag:OgCxfvBglztSJGY0WMIH4A==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:8lEdLSE95IantzwU+U0LYQ==,iv:DDo+FEGjgYUej/+a/JaNOFcV1B/nYbFPAaHzBIHZpB4=,tag:h9BCOIQ5RNn2m5FnwKZc9Q==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:Ofw4dz68VA==,iv:JRhDQVeNJ6nDH9DFXN5TEACiOvBTxUXnYiP44BxsGrQ=,tag:AsJLHKgH9mJKxF6I+V9IUg==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:Mss801qtJDYubw==,iv:/669lf29W52Mq+nGTFvbQNCZCBz+DTt9sG/jAVHKfQQ=,tag:3tUy086hXjxHrT47ewQrIA==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:+08VPtEXmbqUmkhrOWVb9LmbVRffaalhBQ==,iv:uz/JwNHBPg6pe6A7AoS+DRlllSjMNQnDfRNauS7RN7U=,tag:icbNgXLLG31zm5SniDoPSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYzVOTWRqVVFobk5LZE1u
            b1NteWJmbTRBMHo5aXJKanlvU01mU3h0Vml3CmRDaDdMRzFMcE8zUU9kUHNRTVRX
            UXhsYy9rRUdvaEVMTXM0azBXeTdRaDQKLS0tIHRlNVFwTm5nbWtibmd6UWI0VXN0
            d1BKOTJxbUZ2dlFFZFJPdEREUXlXTDAKFZoWmoeg1/vkrJab1Uf9swRGqGhOhOTw
            zFDMEYyB37hPnwy5uTTY3l/GKFyk7orb2p/5ZHjaTh48dxJsrql1ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-11T20:36:13Z"
    mac: ENC[AES256_GCM,data:wxMaGvtcrvRsvfBIt7BzB2MgbzG39E2ZpcTGVymH0eNsbGQNsllooryaOZqKOUA7MC3jX5hZfk35G+XbpKES3zAiKmV8ZcGTjLmBrbB3IQ46o9I6AJ2Yqr3pc+f7Ac2vha78++TAdVs2ApfFjovEbAvVRtIf2c0PwRM41v+SVCw=,iv:BQJpoy9ufes1pQkh0x0gCZ2GixV30joIVuWDE8+oH3k=,tag:gODckG4DfBpxUL2WBykquQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:Ssw/CVceUs+vXqucJ9BRYW1ty+awj7z1dg==,iv:3wyPx7TgTop0vTEIsGhZhqHIKodt1m/MKNw9Y3RI0jo=,tag:6E9MzurQpWQIVXNtOa5b3Q==,type:str]
    password: ENC[AES256_GCM,data:Smw/PowH5yP2SXs/qEV5Et2U/8r/qtpp1w==,iv:IXA5I94XT5NmXEwm79PqoSOEVwHmruFdyFamez0QzM0=,tag:8Qpdd9dk/NWv/NZqAHMZJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYzVOTWRqVVFobk5LZE1u
            b1NteWJmbTRBMHo5aXJKanlvU01mU3h0Vml3CmRDaDdMRzFMcE8zUU9kUHNRTVRX
            UXhsYy9rRUdvaEVMTXM0azBXeTdRaDQKLS0tIHRlNVFwTm5nbWtibmd6UWI0VXN0
            d1BKOTJxbUZ2dlFFZFJPdEREUXlXTDAKFZoWmoeg1/vkrJab1Uf9swRGqGhOhOTw
            zFDMEYyB37hPnwy5uTTY3l/GKFyk7orb2p/5ZHjaTh48dxJsrql1ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-11T20:36:13Z"
    mac: ENC[AES256_GCM,data:wxMaGvtcrvRsvfBIt7BzB2MgbzG39E2ZpcTGVymH0eNsbGQNsllooryaOZqKOUA7MC3jX5hZfk35G+XbpKES3zAiKmV8ZcGTjLmBrbB3IQ46o9I6AJ2Yqr3pc+f7Ac2vha78++TAdVs2ApfFjovEbAvVRtIf2c0PwRM41v+SVCw=,iv:BQJpoy9ufes1pQkh0x0gCZ2GixV30joIVuWDE8+oH3k=,tag:gODckG4DfBpxUL2WBykquQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
