---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
  - ./ingress.yaml
  - ../../../../templates/gatus/guarded
  - ../../../../templates/volsync
configMapGenerator:
  - name: sonarr-pushover
    files:
      - ./scripts/pushover-notify.sh
      - ./scripts/refresh-series.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
