---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ghostfolio
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.3
        env:
          - name: INIT_POSTGRES_HOST
            value: ${POSTGRES_HOST_MAIN}
          - name: INIT_POSTGRES_DBNAME
            value: *app
          - name: INIT_POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: INIT_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ghostfolio-secret
                key: POSTGRES_USER
          - name: INIT_POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: ghostfolio-secret
                key: POSTGRES_PASSWORD


