---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-cloudflare-default-noauth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: ip-cloudflare
      - name: headers-default
