apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    #ENC[AES256_GCM,data:1ioCFg==,iv:TCnd/jgTpSd48CIkB7in9ICkEJK6WsKWTyaxpUdgWYQ=,tag:Qafw6SvN+27nx08ZP1C8tQ==,type:comment]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:FQ1BYy2QybglL0rHP758e5l7NjcQFE1omV7RhTc5HkbkVmBr,iv:5rRmd03xBY9wqr0HTXZ0IT9/7Im86kubRG4GRzpIuHs=,tag:7CdkMIjPo2puWEfucQ8LkA==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:GCorYPASQC+i+F+rlKB0eZi41whw,iv:BPsOm4KUfSESlNkGQA4eKuBdzlIpWoXqIFWCZUof55I=,tag:AQ//ZoaW9tcJ8mINZyJHXA==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:XFqc2Q==,iv:2RORWYSLk8mMR8vsDxz7a+Ur6pxR9vRIBXjAaQzBqjI=,tag:7a0Bz9f9sP6Pg6ZBAuec1w==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:AXDUznaSyRmbEQQO,iv:HT+XXArY0WzQVt7zyIDE9scl2NZffQj0DBhJbfiIM6s=,tag:IrURxNXOYk3uOj0ekOeNRg==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:lf6mzil5kx3RkBlnjDdmMwjFdHgLl37P,iv:TSEpMkiYZ1sWD/O3IGaTR+jheuo55saoSy0MpmkkmAc=,tag:cyA1BdRgGCdwtGOwpLsSDQ==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:5HMOufa6,iv:lHAg2ZSZc9HFOk3SuwR8E0rOf9zEwq26GHxK4K3z79k=,tag:orvg2a3DDr0LFJ/F8GJVkA==,type:str]
    #ENC[AES256_GCM,data:3d0ak7dgB9Dh,iv:kN8SHPY1Ay2qklw0IcgOnzYk3yIzaolBczaB4XHXtRs=,tag:9KM6Ni+pEs0gjUVwC7qYhQ==,type:comment]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:DprCsHPyzwPCiA4jj9qIgj0UyL2xAQUieXnoTzBp,iv:H/MURD7jaZeg+oUw7jhNewgQ28ZnpezF5Jayx9AGoT8=,tag:dmfNJ4OlJtdgXXGAOYx00Q==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:10U7naurC6amxWDV4Xyvtf9Dnas=,iv:RjY5ZUXLE4PNeRihODGw/HRrG2w5MZ2aXOwO6oDIZw8=,tag:zqyABlfGFvM9ZXQRauR6oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T07:32:23Z"
    mac: ENC[AES256_GCM,data:Ie+KKDonW+0u5gE2H6NVvXQsXayglD22Ym1i9o1v05A79zFdUnTlw/s2IiIT4iZG3HZ0WQZ7Nv7co2p57jO8GHbXY58Xsf/Aks4fnIuDmkuqBFBUWXjPvRfB5fwfmCQjSZYXRVwnqm/qqDe7sX+Sahkap7mH2G+4YEpwbhzFBhU=,iv:oNnra7tn1YgACbjbMYfag5eAANUHgBasM5tdP+fTRrs=,tag:ZRxO1csWGcnz1Z9POO1zjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SsarC6hneqs=,iv:Rz9kIuV2+bxuWFPIljOfK6yQ6bVYx0BeWClHjlT8GOE=,tag:133iGZZVp/pD98pKIPr/Ww==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:93+eQLB/cCMZOLcbki+nQVcmBtIjqcjQ64m+UMrwPHdyBoak5TsSAygMiFpbJ9abzoLNybpuOyU=,iv:AgYbTdxwQ+tNXRP5CxkH9H/vod71OwWLJ/lpsG313VM=,tag:hu0DNBzcSkhdKXAtU7v9Rw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ircq+ltHvuRMKLKn3CBKoQ==,iv:u2QZHlFWX/a4HuTPgor+lpvX0WtD1AcBhHhPsVn2K/s=,tag:g2Aucmwn/5ItPZajhU/UVQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:70HlriajbHI39yBgLPL2xsrxQntIWLFWFQJgrrFYfls=,iv:/oPbYNjU/R+Iz/SGR3BOwFaqd0/1smjLiPbWdhSGHes=,tag:1c9AvCS+kVYlMuh+esniEw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T07:32:23Z"
    mac: ENC[AES256_GCM,data:Ie+KKDonW+0u5gE2H6NVvXQsXayglD22Ym1i9o1v05A79zFdUnTlw/s2IiIT4iZG3HZ0WQZ7Nv7co2p57jO8GHbXY58Xsf/Aks4fnIuDmkuqBFBUWXjPvRfB5fwfmCQjSZYXRVwnqm/qqDe7sX+Sahkap7mH2G+4YEpwbhzFBhU=,iv:oNnra7tn1YgACbjbMYfag5eAANUHgBasM5tdP+fTRrs=,tag:ZRxO1csWGcnz1Z9POO1zjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
