apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:fMxwu9Amn0+bn+pMgviCcT9iIEH63s8p/BZdzp9VB+zN5lHfPg2R0ohg27v1eLJnPB7XmwkLcTj3MdVmI30cYyzRKZ+AWVlxxFgxdEkzq/E1,iv:DoVccyj+VTX5TitqHnzS/mb81zoFcLvXYl/8l4+DuV0=,tag:hO3MgJXyKqECoHg3BflKJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-13T20:12:05Z"
    mac: ENC[AES256_GCM,data:LYOMr4OdnCTA03p0hVURApdOdukYr0pFnhIRe3sptGycA3Ir/3ZL9erPaXE4u9vHzGrb4FUYNP0WdUdgQRgHY8MfBs6euth+CHG0uUZJo5Vxn23VKhXvBXF9X8Kmx58GqZ35fLtHFHrgG+gbxdAmaYIZvXAEU1mZBiRk/8AMaKY=,iv:HdK7Ar1JthIIeNhxA6JCTToyejG2v06/wKZ0qTHLzfM=,tag:MXMfTnhAfo+NDOFuhDeVlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
