apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:lr5oZOiZnJ97i3rumcinoeWZ4amr,iv:25PWQuzPpMf58gtu//ha+qFO4YWvi0UMjSUIU7enHFA=,tag:dOtv42sWVgcVvEBviJh0Lw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:CmFeRZwJTUxs+fwcolLbYz37EAcIjLzCDNANmHl5yw==,iv:NuKmKg7/W8hYj8PXj3SvcAzjhEZlIxlQeJEHVYNMbGk=,tag:1AvqN7yWjg9TClWfvAMCtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T13:10:14Z"
    mac: ENC[AES256_GCM,data:ue48k7RzLY9Ru9n3+m7SCD95AQ0JxMRj1jF/8si7XaMuTx4hr9wcQmaQLhmaEgjN/zkMGhT6DAEdrQtGG7sohsZFcGI4mEQhLu77N9SL9zPylKMZemR2uymKjQ/VqCMMWfaM131RsPRohg3PzVmBVS+eML56taAzijTBmoPNJUc=,iv:Pvr43D5gMGLLx3VosFvDXRxgRvEOxkoCL57VMHjrtkE=,tag:LzNTfJ/RBRRgPqlh+2L5hQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
