---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik
  namespace: flux-system
spec:
  targetNamespace: networking
  path: ./kubernetes/apps/networking/traefik/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cert-manager-issuers
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: traefik
      namespace: networking
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-add-ons
  namespace: flux-system
spec:
  targetNamespace: networking
  path: ./kubernetes/apps/networking/traefik/add-ons
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: traefik
  healthChecks:
    - apiVersion: traefik.containo.us/v2
      kind: TLSStore
      name: default
      namespace: networking
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 3m
