apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: postgresql
data:
    username: ENC[AES256_GCM,data:duzCBHec65aDNCVorjO3j2pREFwiWwiSoQ==,iv:8ato3AfQI9PNLR5qmyCFOHcVoEQX04WMp9uMJgLInGI=,tag:6K6ilUHCF2CWXbpu9ME8Qw==,type:str]
    password: ENC[AES256_GCM,data:iYnaAaOIAsjhNr+nyjqQd4egK3V/KIdxuw==,iv:i0w29CXf20mj4YV7yKtYfkBVFh4xNgoThMeYsy3XlPE=,tag:r0ZGeqFtD8Tp7eTcM2tFcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OENPZjhvaVgzbTAxL2NL
            SmtSd3FLTGRxdi9pQTVsMzM4NGNaSUx4UWhZCjdjaTVRNnI5WStmbzBFRy9LTUJO
            cnpzbVNlUTU4R2I3d25CenMwTTJlK2cKLS0tIHlrSENUZGJ1MkJkNlNnTjYyaDBo
            ZlU0YXhpVXIyZC9DWTJFWlR3SzI2cG8K2OmW0yGJ2ERh3+r1CAO0ZtXIOv1tSadS
            J9O2+wYwspAA1hGbHuKHELHwmNhwNXwzQotHLkcIR9xODEDWTtDgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T21:26:36Z"
    mac: ENC[AES256_GCM,data:tsZDXrOVgfKcRxhYzUdOSbZnxfwAnvUSMEQcy+Q5EcQ/BqnEpxcUgsWOgLL7KwpWh6DD5rGEXsM7EcD8HjjJLbHJhrR5Pi/SOHsDW/cFy6dEp3DdpzhBgoyDa/GwfT7645WS4sYJw7jn2TZJLU7s8lwD7NyZuVV3S+8C7ICw/kA=,iv:GtKwZsIQkXVxcxbJUABij8UIjZ2bryppYp+9UtbY1cE=,tag:xrKi+OrcYeTIzRXZmOes/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
    namespace: postgresql
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:oR+TnIR2Fra3OnjWNDk/dnCott0=,iv:wcY+lhHT9HxM1H80mtE6qbAJD5/LA61vvPw2SHbBmKw=,tag:LjJOirMl4CwCHBQmvjstVw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:fhj3iazzPf9UoeFISXxw/ekB9EOUlLv12pjiuah5IRzvX7GQsc334Q==,iv:E2V2bhb+2qz4vLnV5TTCqLhEiTwqxz2tMan0pX8KtRw=,tag:REMf6+uwxifvOOEtd5cAwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OENPZjhvaVgzbTAxL2NL
            SmtSd3FLTGRxdi9pQTVsMzM4NGNaSUx4UWhZCjdjaTVRNnI5WStmbzBFRy9LTUJO
            cnpzbVNlUTU4R2I3d25CenMwTTJlK2cKLS0tIHlrSENUZGJ1MkJkNlNnTjYyaDBo
            ZlU0YXhpVXIyZC9DWTJFWlR3SzI2cG8K2OmW0yGJ2ERh3+r1CAO0ZtXIOv1tSadS
            J9O2+wYwspAA1hGbHuKHELHwmNhwNXwzQotHLkcIR9xODEDWTtDgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T21:26:36Z"
    mac: ENC[AES256_GCM,data:tsZDXrOVgfKcRxhYzUdOSbZnxfwAnvUSMEQcy+Q5EcQ/BqnEpxcUgsWOgLL7KwpWh6DD5rGEXsM7EcD8HjjJLbHJhrR5Pi/SOHsDW/cFy6dEp3DdpzhBgoyDa/GwfT7645WS4sYJw7jn2TZJLU7s8lwD7NyZuVV3S+8C7ICw/kA=,iv:GtKwZsIQkXVxcxbJUABij8UIjZ2bryppYp+9UtbY1cE=,tag:xrKi+OrcYeTIzRXZmOes/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
