apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: postgresql
data:
    username: ENC[AES256_GCM,data:duzCBHec65aDNCVorjO3j2pREFwiWwiSoQ==,iv:8ato3AfQI9PNLR5qmyCFOHcVoEQX04WMp9uMJgLInGI=,tag:6K6ilUHCF2CWXbpu9ME8Qw==,type:str]
    password: ENC[AES256_GCM,data:iYnaAaOIAsjhNr+nyjqQd4egK3V/KIdxuw==,iv:i0w29CXf20mj4YV7yKtYfkBVFh4xNgoThMeYsy3XlPE=,tag:r0ZGeqFtD8Tp7eTcM2tFcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OENPZjhvaVgzbTAxL2NL
            SmtSd3FLTGRxdi9pQTVsMzM4NGNaSUx4UWhZCjdjaTVRNnI5WStmbzBFRy9LTUJO
            cnpzbVNlUTU4R2I3d25CenMwTTJlK2cKLS0tIHlrSENUZGJ1MkJkNlNnTjYyaDBo
            ZlU0YXhpVXIyZC9DWTJFWlR3SzI2cG8K2OmW0yGJ2ERh3+r1CAO0ZtXIOv1tSadS
            J9O2+wYwspAA1hGbHuKHELHwmNhwNXwzQotHLkcIR9xODEDWTtDgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-18T04:16:21Z"
    mac: ENC[AES256_GCM,data:jDeCpY59QcaA26wpHONmjhGUOWH0t8gOoCoYbqJht5k1S86ZDZ6mejYAgmMv9UZQFCONBqaweLbtFS73AErx5uds/Ke6Si/nMp9GoTV4B/+P5X5aWTU8IcYSlLlY2TndB3OSzJKs2HvyPTzAT/KNN1p1WW9SYtXhlga6U7JVkHM=,iv:6RsZiT0eM4h1ylr63Qn19bLC7lpVeTW5tvcpXxOsKIs=,tag:hRYHJroTFflToLlP2LFLxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
    namespace: postgresql
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:s3AUhEId0JOxosc4CZzIfcdgQVo=,iv:ffubmVy7CfQ1cGjptqW8zGAW4ySM/VBVBAL2eHC4u7U=,tag:qt3C3o/APke22HSI/S4ljA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:jWh5NsdAvAlYcPMaWMwaii0Ln880RGHKErtWJTdYfz53bhi8bOvfBw==,iv:l2pGhvuJ7HVWz/vVd1nBBg4ETZLb/Fxskfmx3/EagOs=,tag:WHHJm0Fad500BzmoZR0k4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OENPZjhvaVgzbTAxL2NL
            SmtSd3FLTGRxdi9pQTVsMzM4NGNaSUx4UWhZCjdjaTVRNnI5WStmbzBFRy9LTUJO
            cnpzbVNlUTU4R2I3d25CenMwTTJlK2cKLS0tIHlrSENUZGJ1MkJkNlNnTjYyaDBo
            ZlU0YXhpVXIyZC9DWTJFWlR3SzI2cG8K2OmW0yGJ2ERh3+r1CAO0ZtXIOv1tSadS
            J9O2+wYwspAA1hGbHuKHELHwmNhwNXwzQotHLkcIR9xODEDWTtDgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-18T04:16:21Z"
    mac: ENC[AES256_GCM,data:jDeCpY59QcaA26wpHONmjhGUOWH0t8gOoCoYbqJht5k1S86ZDZ6mejYAgmMv9UZQFCONBqaweLbtFS73AErx5uds/Ke6Si/nMp9GoTV4B/+P5X5aWTU8IcYSlLlY2TndB3OSzJKs2HvyPTzAT/KNN1p1WW9SYtXhlga6U7JVkHM=,iv:6RsZiT0eM4h1ylr63Qn19bLC7lpVeTW5tvcpXxOsKIs=,tag:hRYHJroTFflToLlP2LFLxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
