apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:itFhzruE0FNc5QKyRdGyDtMYMHyKbhQlnw==,iv:XhFsCyYG24u2Z7x3QwmPXp5mWEg4oacm1X+3OkvcTeI=,tag:GwnbJYBxbqIEc9V6eWXLLA==,type:str]
    password: ENC[AES256_GCM,data:n+Nb6B0aeeozcFWVHxRe5fCcGfmgUKsCOQ==,iv:OQ0wYBzbE1cwEZ/RMhvkL5VReQCUJOf7fpiSsK7c2rg=,tag:2shM9sGmFbEPnsqfxJrNzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:35:50Z"
    mac: ENC[AES256_GCM,data:+L6Sp/Ez+Ku9WkRyWpAJ3fcnZWbr0VimahGNBx5KlODdwESPPxf1bhmvkt+bY8pb3CB9rs+9cCJ81sM2YZ8DZRpfrafg/9cOoc0BSkrJtOJ92TruV+6ImuxFKk3YFdlumF2TqI+HDM18OLjwDumGQlwN97zZ0be5XvxDavg5lHQ=,iv:2BsANyNTAUcozM8YcM+nVwIJTKH28F6AILlr4A+oBdo=,tag:qcBL1CJ5luoaSX+gdBcbGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:8D+3UdSRWYO6/qd0USOWUpOdjPc=,iv:JDl5dGIJPCai2aICFqi6NZMWqoTGZHq+CobMXsayVdI=,tag:vWzCCTzmaYn771siB/NpJg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:D87EG/cbChBBSSAW9umLOy20yB+JSIltIgM4xhFk+GfxsOTYi7FvFw==,iv:mC9q2/zixVjb8BNoboxPOKujQjM0m0atTRCEZYyqEdI=,tag:OJ94TsM1Mqq/Zsy3M1bvWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:35:50Z"
    mac: ENC[AES256_GCM,data:+L6Sp/Ez+Ku9WkRyWpAJ3fcnZWbr0VimahGNBx5KlODdwESPPxf1bhmvkt+bY8pb3CB9rs+9cCJ81sM2YZ8DZRpfrafg/9cOoc0BSkrJtOJ92TruV+6ImuxFKk3YFdlumF2TqI+HDM18OLjwDumGQlwN97zZ0be5XvxDavg5lHQ=,iv:2BsANyNTAUcozM8YcM+nVwIJTKH28F6AILlr4A+oBdo=,tag:qcBL1CJ5luoaSX+gdBcbGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
