apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:itFhzruE0FNc5QKyRdGyDtMYMHyKbhQlnw==,iv:XhFsCyYG24u2Z7x3QwmPXp5mWEg4oacm1X+3OkvcTeI=,tag:GwnbJYBxbqIEc9V6eWXLLA==,type:str]
    password: ENC[AES256_GCM,data:n+Nb6B0aeeozcFWVHxRe5fCcGfmgUKsCOQ==,iv:OQ0wYBzbE1cwEZ/RMhvkL5VReQCUJOf7fpiSsK7c2rg=,tag:2shM9sGmFbEPnsqfxJrNzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T19:36:58Z"
    mac: ENC[AES256_GCM,data:etXfSI/8sh9DCIp6T/dtqHQCVFCzQbXbkzlNA5QF0hoRUsM3e1Kr1eTpyvyejt/lw6bkXK+y2qa8M+3wU+Sv0JdIwWQzaA63qRTD4s9fE44JQZWAHVijLz6uUYFDjrtITNr3upFGOgZUt5DppYv5EmTiU6qiPgxxPtCUhu586LU=,iv:4KsIW54pDyctH6HR3jgudRpWzx9hlrkJkeiOYa1bPgM=,tag:OG8E+q74fl8Cadl4x6WX0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Eebh6ejfxeMH0aBdW6Lf9FV4kqA=,iv:O9rwQCouy0aYwJqDxMoAe5Rc3KD6LAPa2GUVsLodPrg=,tag:SpJhJdzR8TAMJwtuav9+oQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:55Gq8bp7omaBoGeh/RdEnEk+LFIuHU4Q/wSlSuOH9N8AUwQZQAdAlw==,iv:Qav7HQ5QRYteqHw+V1frC4qZe3gOQDSn+zn0ZrMj8LU=,tag:G4e8cIBpoHJmPEjxWpzlPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T19:36:58Z"
    mac: ENC[AES256_GCM,data:etXfSI/8sh9DCIp6T/dtqHQCVFCzQbXbkzlNA5QF0hoRUsM3e1Kr1eTpyvyejt/lw6bkXK+y2qa8M+3wU+Sv0JdIwWQzaA63qRTD4s9fE44JQZWAHVijLz6uUYFDjrtITNr3upFGOgZUt5DppYv5EmTiU6qiPgxxPtCUhu586LU=,iv:4KsIW54pDyctH6HR3jgudRpWzx9hlrkJkeiOYa1bPgM=,tag:OG8E+q74fl8Cadl4x6WX0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
