apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: postgresql
data:
    username: ENC[AES256_GCM,data:itFhzruE0FNc5QKyRdGyDtMYMHyKbhQlnw==,iv:XhFsCyYG24u2Z7x3QwmPXp5mWEg4oacm1X+3OkvcTeI=,tag:GwnbJYBxbqIEc9V6eWXLLA==,type:str]
    password: ENC[AES256_GCM,data:n+Nb6B0aeeozcFWVHxRe5fCcGfmgUKsCOQ==,iv:OQ0wYBzbE1cwEZ/RMhvkL5VReQCUJOf7fpiSsK7c2rg=,tag:2shM9sGmFbEPnsqfxJrNzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T21:30:41Z"
    mac: ENC[AES256_GCM,data:F4DMSPD2rpttpC6UyzUUv9fNCTCXnmbYMT0LPfLABhhV/TPm54WxOGMWL28hmd8awEI1iKXATB1pnrBE+o61sCt2wGrPZDlAFKrKFDW2MtYmZAy8ZvwTMSNkCm95zrzDo/IcyPAi8qGDOMCS4VERjvV17Ma1AvAcbNa/KSVkWT8=,iv:KdKQAb+9TW3ivWz6y0H+R/YuGBCjaK1ks8GqV1yuk0U=,tag:ckkhBFL82gTvsHMz07kc9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio-secret
    namespace: postgresql
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:8D+3UdSRWYO6/qd0USOWUpOdjPc=,iv:JDl5dGIJPCai2aICFqi6NZMWqoTGZHq+CobMXsayVdI=,tag:vWzCCTzmaYn771siB/NpJg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:D87EG/cbChBBSSAW9umLOy20yB+JSIltIgM4xhFk+GfxsOTYi7FvFw==,iv:mC9q2/zixVjb8BNoboxPOKujQjM0m0atTRCEZYyqEdI=,tag:OJ94TsM1Mqq/Zsy3M1bvWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T21:30:41Z"
    mac: ENC[AES256_GCM,data:F4DMSPD2rpttpC6UyzUUv9fNCTCXnmbYMT0LPfLABhhV/TPm54WxOGMWL28hmd8awEI1iKXATB1pnrBE+o61sCt2wGrPZDlAFKrKFDW2MtYmZAy8ZvwTMSNkCm95zrzDo/IcyPAi8qGDOMCS4VERjvV17Ma1AvAcbNa/KSVkWT8=,iv:KdKQAb+9TW3ivWz6y0H+R/YuGBCjaK1ks8GqV1yuk0U=,tag:ckkhBFL82gTvsHMz07kc9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
