---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: &pv2 paperless-nfs-data
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: *pv2
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${LOCAL_LAN_NAS}"
    path: /volume1/dev/documents
  mountOptions:
    # - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs
  annotations:
    pv.beta.kubernetes.io/gid: "65539"
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: paperless-nfs-data
  resources:
    requests:
      storage: 1Mi
