apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    #ENC[AES256_GCM,data:hwoZDqYtO7lTjQ==,iv:0RyrUU7xFUjPGPb4S041An95ZrcZ2I052JSyIohZik0=,tag:a2zOfdeAqsK/Wr+K/ZNHwg==,type:comment]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:nahgTfQE6EXenp1RxQhK4b9EJbuC,iv:guIbpJqRwM9yQwvv59P0IePqKXX9Ig/xhyoY7H9boPQ=,tag:IzYE1smKK1wZiclWWAPk/Q==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:K2njRUrxlWzXvUmIP+xloguk8cDxGduw,iv:48dKGIsPgNgvZSEQ4Os8DQYGhny9XSDKwQ1lzb892co=,tag:pRl2p+zXJ6xlnLMJ+ybhvQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:yY/I94YJ+4UStSibAbYP1FJ70vvA65nqrKEssaRk24p8/3bWzdVVosj8b5e0kjs4nsdc9Xq7ni3QP84j/hlIFA==,iv:LO+VVCZdMM0jaEX7ZMhEC0wytB+sLI7cTuFrjoc69Qw=,tag:/ghWAQf8Ps4jwKqphcnFmw==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:hVeVQjTM7Q37,iv:VtG9ln1uT31iWbpxhB8KA6fewgyWaDGVVOTZItI5IqQ=,tag:VM0HqKWBLvbwyYBz4quhZA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:Y3hDUOMT/2e6BxZ2yGf8WT0hVxaczXHE,iv:JAsAgtaDbHF4p7qK8K09fZrulda0j305TfUXtQ3NsvA=,tag:svANRPrs2A/utHJU/juiiw==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:Y2o6PYFy8mvf,iv:3aFf4mLwNcZ+zBYOYIndkePf1aBEEo8D8L21adPqCS4=,tag:SUnCveqX7b0s6ZnsPBShVA==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:OnhD1K5KDJcZ9EJs2IJnz8kEdJqG,iv:SgzvGKbWyKhrYzE9qsgpFKE8mU0W99H6HMnvEAw372o=,tag:LcVofMEIXj5wYRkhh+IyXA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:v1v2VQ==,iv:z2E2m7DMyn9bHV42kpHYbGlkoPNiI2CuDIw4Ywxjv3M=,tag:cgtIF/bbVrGu5/Q+HhoalA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:J7n7QdUoqa3UEz31RjIUtaLnNl0q1Dpfa/rrZRNW9y7rcXmudVm9gmqVzSvMR1C99DNNxWdRPohtx0zf9YX0b0sRHRKxYJQyzHplKUSa1nnTuDdHI/ovUvev94Kl5OkmXg4FDcCRAvwDPJvJPWLtaSj7fQWpcUtr8etnNthRM/6GF6q4Exq1fKK/YAElUhtM2By2IKWKLuCDrnIzV+mkQJfxYtLpPAlcpIP74tCav/8qpwCSHpBiHo3gP9W9syLoqLemkduH+V9OObGzMQOwiW56zV8tONXZyrjBVB6rxt/HGx/IcWEzGc3JE8Gj+V5k+nkFyqJfuKkCInRpwVO9IZ+eaWlRGMshD73aEVI44Oo5dbF4BWYqnhbOl3s/BxEaTH6grAYkRA1yL6JyHl3t1+I7mJ3KE784HWt5an8yopXsvOM9CF+k53x3yfzgIBxmBCDa14gll4A0k+PvfkqOzLFiuMArZQI=,iv:H/XyjuSg+tTJZqhGanAsy0gawYinNCTwEAO76Qu7vQI=,tag:PbObfCRa6sIZ20LkffgATw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:23:50Z"
    mac: ENC[AES256_GCM,data:ELFkedsfy5Wfd0nyVylA/b8xGxIpWLSd5zDVasic02ZZUoBn/oWkTEBM0qierJIBqNyWxNfsa1B0nuVQq0fxuNTwd8INHNVkBKHbpHSh2vhkqxuUluHBw67JZK1FB65BHlzluMnGMXAzVrzSBjIQBAVzRcx2rjSTSvno+hSPIgI=,iv:FlyZXIWp5GA91N9lKgLq7S78m4sA3MsXBBB6Ruol5RA=,tag:ACvZM2RJfKfT5OlWOL37GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:BooFYG31jMKmdwCZ,iv:FtLXboWWJxq5lb6kA8xkCJ84cZwfkj4EjMnkI3fBfCg=,tag:CXI92eMo97s+rRbUVQAJJg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/YJ5lygeszrIvvnGD1Vxbi1SuhHE460WhGPp1Lih5LtPs3hE152rskoaLok6mr0ZdBfleEJ04Zo=,iv:vI6PY/gBqdTxUOQfFrB4CH4Q9VBFMVlIUEhFFHCNfls=,tag:XLl/+TXVGMAXQb4sqAAD2Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:10bN1tuqq9f+yMhx,iv:YzWmslg5qTDA7ca2eJ/TqTKtLQc+dbemwYnscp7oXmU=,tag:+bBxxsATL8z3bhpIJp0jhg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KdhRlj+mn95cagm1mHfahRe94fSMGcTEc90aR/sOzMI=,iv:l7S9gnpq2vJE58MlSVpBxGRBYlfMcaUh/ZxZ/iKgR9o=,tag:9j8zxsig6c/wHkUWRDS9iQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:23:50Z"
    mac: ENC[AES256_GCM,data:ELFkedsfy5Wfd0nyVylA/b8xGxIpWLSd5zDVasic02ZZUoBn/oWkTEBM0qierJIBqNyWxNfsa1B0nuVQq0fxuNTwd8INHNVkBKHbpHSh2vhkqxuUluHBw67JZK1FB65BHlzluMnGMXAzVrzSBjIQBAVzRcx2rjSTSvno+hSPIgI=,iv:FlyZXIWp5GA91N9lKgLq7S78m4sA3MsXBBB6Ruol5RA=,tag:ACvZM2RJfKfT5OlWOL37GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
