apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:WqZzNiDGpr2Zp/sl,iv:sgwjVst+jh78K7SnFdi26Rh0wvCUsZ9aIpjdKjUMGio=,tag:30b2UXdxaDOtApG6DIAO5g==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:mw9ManghiwT1dbg=,iv:kOvwqErfGGRcdQbDK/zP4W4CcVBTxhhgAfp3z+QRlaU=,tag:xHOaOLhuU3H4qolI0M1pJw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CyN9rw1p0MFbGwV3aw4FXM0jroz9Giqs14Y=,iv:maq9uMYp9oDvGcE2ycgRyv+H+cjylKbIB0QqFsqEI5U=,tag:o8y7ZPXfYx/cro/jJFB4zQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:HnwwrS/h9UfRMB6QUYggcDlqSAp7xxo43w6DaumCHiA=,iv:hGtUB4nlKweMvADQ6maP982Httdf3KTEOE9lKWzlFH0=,tag:85rHyVMdAVnkTzeK47Z2ow==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:EOGXAcPGo4Ym1TTdS+WpHr64lHa4srI2Qvk7Cod0uzo=,iv:WnZiYB7TmvagmVFaf1IYDC+ZoqAZlEO8DJ9sQCQ2H3Q=,tag:Ea8Um1N5aQZOJVbLwM0MCg==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:37Lo,iv:A3nyHjSJwr/TT6mhKZJ/S/34mC4/gpv1XLKcGdpd7OU=,tag:2Mg3mCAknpCMkHjSryRT0Q==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:K6sRNh2lVV8koofubtXXVqmKpA==,iv:Z8R8LWX+FhCVKlib3+2OCWtlwb/oOsswTbc4yqKi26A=,tag:bsOKf9eRBO0CXzbnz+uVwg==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:wgJG,iv:4q/cE/plkneiv5MGSR2w6Mw9cZR8lz4mo0r3GOp19J0=,tag:uVRxEDeKpTMZAl+xM2Zt+w==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:q3OLtBAjr+SiduYgk8k0cS5do7x/Yw==,iv:YeyhQ3H1dywNGE1WuszOEa/JnfAFJpNlYbhoAaCEsig=,tag:aoNfMiyhcJMnXzYQuzcdiw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:VbhXRN98Cc+qtvsJcTWcbfX0yA==,iv:Ze+z6j1KxOD7ToY1W0WnIrroKf0Jk9lskjBrxrzxtf8=,tag:exQukM6wfLmyErQVzqrPAQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:0ZdZ1pAh3q8z38/qiWTyP4s18w==,iv:RZUXgOejJY8xwqyQYqIXboBehgTfBPATHjfSdriVByM=,tag:2U+dY40W4StPc5kM7/hN7A==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:eYiS8fpmjFA=,iv:gCiHaOGV1812IjCWSKgrio3v/lSnLswuLQTTCQVTofE=,tag:ZdNDxjS1YPwOHxREmpkxSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:20:48Z"
    mac: ENC[AES256_GCM,data:PZpsiLRj5pnAhB6pI6lAcl28snP8ReaypzEtfU2/zPD9y+KiE81Vtb/7UagMHDzhrQX/JYqzB8D9ipfM1tYH82AJiMj6kKl/VlV+DXiR+PuElSakW5ZRm0EHzGxMOHz9jLJZKOl+XzaD0P+4beII0JHx5xcphpTjQDNEOHIMqzg=,iv:MprRWEl4eB92mUJ+Eg6T9sLp9feBnI/x9giLfWHF/20=,tag:buT9RedqD1/R+wCGIFr0zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:vSwVyMSbZpplsn6SPv3DNrczcZNGsCf7AQ==,iv:IwdVH46BTu9nEKRi1ocrVDwZeEuvAjOIXmAPlCaMjQM=,tag:OLuUpILobU6gTT1cGhBCEw==,type:str]
    password: ENC[AES256_GCM,data:yu5R9vIv2FMgeRBQ39ppfnr5iSIzTin39A==,iv:85NpEwbUVANa8A2bbcubOicntm3XSIFSM0J5gZlUohI=,tag:/MQq+NPJs8LjdDITgv5h8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:20:48Z"
    mac: ENC[AES256_GCM,data:PZpsiLRj5pnAhB6pI6lAcl28snP8ReaypzEtfU2/zPD9y+KiE81Vtb/7UagMHDzhrQX/JYqzB8D9ipfM1tYH82AJiMj6kKl/VlV+DXiR+PuElSakW5ZRm0EHzGxMOHz9jLJZKOl+XzaD0P+4beII0JHx5xcphpTjQDNEOHIMqzg=,iv:MprRWEl4eB92mUJ+Eg6T9sLp9feBnI/x9giLfWHF/20=,tag:buT9RedqD1/R+wCGIFr0zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
