apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:WqZzNiDGpr2Zp/sl,iv:sgwjVst+jh78K7SnFdi26Rh0wvCUsZ9aIpjdKjUMGio=,tag:30b2UXdxaDOtApG6DIAO5g==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:mw9ManghiwT1dbg=,iv:kOvwqErfGGRcdQbDK/zP4W4CcVBTxhhgAfp3z+QRlaU=,tag:xHOaOLhuU3H4qolI0M1pJw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CyN9rw1p0MFbGwV3aw4FXM0jroz9Giqs14Y=,iv:maq9uMYp9oDvGcE2ycgRyv+H+cjylKbIB0QqFsqEI5U=,tag:o8y7ZPXfYx/cro/jJFB4zQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:HnwwrS/h9UfRMB6QUYggcDlqSAp7xxo43w6DaumCHiA=,iv:hGtUB4nlKweMvADQ6maP982Httdf3KTEOE9lKWzlFH0=,tag:85rHyVMdAVnkTzeK47Z2ow==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:EOGXAcPGo4Ym1TTdS+WpHr64lHa4srI2Qvk7Cod0uzo=,iv:WnZiYB7TmvagmVFaf1IYDC+ZoqAZlEO8DJ9sQCQ2H3Q=,tag:Ea8Um1N5aQZOJVbLwM0MCg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:bSu8FPkIkGx7G5AcfJ2xHNfFtwsVbZP63WUQQV4=,iv:20Gpqgeberw6+NGl+H4eOBY81J1WBURGOYRzxKkL2dQ=,tag:jl7Y1KaSVdRdZwMQabi+xg==,type:str]
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:oOsvAA==,iv:pepGBk62/4WEy5VEmkY2T7LZ2tA9NpQOlC0keXlkWnA=,tag:dmpkY2XPlWOSZYpFaixjXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T07:58:15Z"
    mac: ENC[AES256_GCM,data:RDuL6PYMdhhF3ZrOvCOquvaBe7SrVW5D+C0I7+432zA5/JG7QN/iQ3Ppjv+E46W5Xz1NGlt8v1oA7KlewmWLf4z0M2GMLEyxktEqiJ29nXkdMABVRQMhxRMC/fcxRkeXCnf+tCbz3p8a1I5sli1VGa42YBmbW5H1vv34Zk+xVww=,iv:c76+eym+P/gibza6s5xuQDGvmHBNUUa4udnoIJSpuBI=,tag:IpYPI60CSpaNFCVfE6aS0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-init-db
type: Opaque
data:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GsvrdLrsS1H4N3e9i6aSBw==,iv:wi2WVvPt6TOLDH5Bg8PYLaVymWWmkSQysLVzCRfzqNg=,tag:ciOMKpp3lpi3EjiF10caUw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LAMTls0IMuU0uI5NgKUwkw+g+HZlvsUtFl7mHQydvFFs7f/yqNa2QlzLr5xtPoCEVJ9YsnP2xSU=,iv:zM2dOpPIBrE5+EXItriaUw/HjnjK1T2eZ9XDY8815qU=,tag:LbJxqJwrIa8dmW8KmCf8OQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:vHjFyMUdIU4HexUHs+O1MA==,iv:DG+dfyD2oVyvfc+GcAkzajuVfrG+C9rzlP/CM4wNqtk=,tag:O97j/82HGUTRdpkrlUC7+g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XbearNvtOr+NOVK1jQTYncf6XE0Cex/ISnOxfW3WdNJ89QV4,iv:MlZfAZFkllJF+CbCYalXWO9Sg8wagf9K7OOYEI7DEck=,tag:Mxodb/g4krU//u0042lsGQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0wVPtCVfP3wHFiDloBZpxjqxXetkugEBIA==,iv:lspRswPLmcZ7LyRfYn5Y+6eFey3lEvZow31Hqs14okM=,tag:as5IRQsMK4ojjmw0urT+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDlCMUU1dlk0TXZ0Y0NW
            RDMyYmUvTTlXRjhIL0JhWkRsbVhPSXJKMVZjCmRHTE4vYkZyQ0VHQlJvY1QzSFFF
            Z3VWSlE0SW84QzNhNDB5cjl5ZUtqN1UKLS0tIC9jaUpBYm9kTFRMNldIOVpmY3dN
            WmtQVmFTOU0wZGxjODFaVnFoQVhqczAKtu4GulcZabUrbwdixrm9O5ITFLeY/Y2b
            x/IyWGZD3tsDaWd3+XwcudHzBodfEj/TRUJt5AWscn4jRIG+GOI1Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T07:58:15Z"
    mac: ENC[AES256_GCM,data:RDuL6PYMdhhF3ZrOvCOquvaBe7SrVW5D+C0I7+432zA5/JG7QN/iQ3Ppjv+E46W5Xz1NGlt8v1oA7KlewmWLf4z0M2GMLEyxktEqiJ29nXkdMABVRQMhxRMC/fcxRkeXCnf+tCbz3p8a1I5sli1VGa42YBmbW5H1vv34Zk+xVww=,iv:c76+eym+P/gibza6s5xuQDGvmHBNUUa4udnoIJSpuBI=,tag:IpYPI60CSpaNFCVfE6aS0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
