apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
stringData:
    #ENC[AES256_GCM,data:mli/sL02VU5nhzJc,iv:HPGsWWY6a2QxCGB5iCuIVoMWoOZHoCdqsQiJK3VAfC4=,tag:niNtT+OejvdkODGpNTcHNg==,type:comment]
    DB_USERNAME: ENC[AES256_GCM,data:CEj1uAQKtWfNsxU=,iv:sCVk+fwWXLafAkFeaSw50Mre353HSZqdqLeu9rsG8pY=,tag:An70A3fhU7qY7RYEkzmYMw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:DcLJjX668ng7BbWMXetKuyF+/HBzSPmruWM=,iv:4obLYzyRO1eS+rHNJHDrOWjklTg7FUMzoMVank/aWgw=,tag:CbOl6RhAN4VKr2nRTis0dg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:ni2JRHcIKqjMNcIHV/6cs7W+jmE2ijMEUXNlmzILpHk=,iv:FSvAv5lm39nDbTW26NZ4P1gVq8Y6v3MHO7IqS2pbCJ4=,tag:dRZapEt8pu0BRUr7f9nC1A==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:sMM+G/iaJivWs4cvmdMYOuME1EuIkLXYHIxzmyY+UXY=,iv:ZPvMGyYxZlsPvO1EXeU2eiSQjG6aPs5rVUBUpTOF3jA=,tag:ZTMRl3tWIt+dqC0n0MVMPQ==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:kZIR,iv:ZxQKEX2v2K40/EoxiDFs71vvn2EmjbCh1HtxgGC+69s=,tag:4C6lBiNu2+yNzPW2TQBZgg==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:3kg1ICCVzijxSIEp652LRQertQ==,iv:O+MQeqFnmf4VNm2BbUd/PwYHACRy+4/ZKXrs2ZdL3hI=,tag:OyZlDmNtY8kSioybsNcvwg==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:fQrR,iv:G9TPqEm344Fk0vvMR/UiZserAF2snDchwg1mkjAUSyg=,tag:AT3p4X8DvwFWUozQcDO+Cw==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:fjZ/H4ybY/KuCazH/J8fVtssF0V2Eg==,iv:sj5Fr2EzNHWwLxXW/SBT8tTaaQ1IL1JCSbkGI2V1Azk=,tag:AjokuUnHpx0PaJly+WKV8w==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:SWpfaUc53BotGhErpjJ1N+F4Cg==,iv:EvKkcIkWcn4p4ClV+IWnEUFPgWGZlvaP09dhlkCyb8w=,tag:ZI75AMYFyDhJSWfuIwaePQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:q6kYfe3v/kXaJMbL2XWT9Rtn0Q==,iv:kiRzPj8tjRcUuxxdqJtThUeOkdlWIKx008BmOxZdbd8=,tag:qyfPNpSrEW74nuHselHV+Q==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:KEwm+ZR+prs=,iv:mocH0uBq9WyU+YgyiPnKoJ8PHMJa8Qks+xiO+srM/VY=,tag:K8fW6lBhBPe64X8ZkPlFhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcnlZTGdLRGcxZC9KVUk4
            dkJ6RFpvMFJ1ZzFtemJqQklkODNWU2h2U3o4CjlTdER5bGJEak8rY0t4dGcyYjkv
            T2hPQU1pSlpZb2JpalZjMityREhaTW8KLS0tIDRxTVgzWittK1RkeTlURmd4VkdH
            QTN6V0pFeUpPL0sra01ITGVXMjcvNkkKhguolUk3iJx88LP9X9bwkBfoPm8Cb7qi
            K1XjAhdesnIv22n50VZoPQnvhfkCRID66ab6pRQ0/AO/KZp0PUdo0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T07:02:34Z"
    mac: ENC[AES256_GCM,data:wbIjL6Gtx+VgyLy/9OB7Wx958IKcvWgAhZjI9/e4j1oxVcWwdyIu5ci/IKRhOWcqcfg//GO1wSw4SEb3HZB3SfNnAggpZ3i2W7I7SpAyxcj7ljmEu67tDkSvYThSmx33QrD1EKb49A5gJaMAED8xfBTHTfLuTfGMAwmJLSss9sc=,iv:I9sn3mA3VkLRFAq+PR6Vi2sh9aeAuQg7FwPRGFnR2Oo=,tag:9LtsbfTv88qNoJaZQq25mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
data:
    username: ENC[AES256_GCM,data:NyylfnANFgyw1aV6Efqik2z4FY/oOinmJQ==,iv:MVtBmK6sunN4Bqnhllqef3IOV+dF9D82aGueKcBM9Nc=,tag:PJVu5eSQM4HJXQwNGxP1HQ==,type:str]
    password: ENC[AES256_GCM,data:R922MFhYiPgGD13EiI8giTl/5ltX1uq0aw==,iv:RUM4h8wENp6118hJqRBi6kNCzlCSu3dplwjDNo4rDrg=,tag:XBYppQfcPuWaNokUmkDXpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9te9uhv3e53vx52zrxvfv5g22nj90l9m5zzv0seag99qcay4f8sjc7l8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcnlZTGdLRGcxZC9KVUk4
            dkJ6RFpvMFJ1ZzFtemJqQklkODNWU2h2U3o4CjlTdER5bGJEak8rY0t4dGcyYjkv
            T2hPQU1pSlpZb2JpalZjMityREhaTW8KLS0tIDRxTVgzWittK1RkeTlURmd4VkdH
            QTN6V0pFeUpPL0sra01ITGVXMjcvNkkKhguolUk3iJx88LP9X9bwkBfoPm8Cb7qi
            K1XjAhdesnIv22n50VZoPQnvhfkCRID66ab6pRQ0/AO/KZp0PUdo0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T07:02:34Z"
    mac: ENC[AES256_GCM,data:wbIjL6Gtx+VgyLy/9OB7Wx958IKcvWgAhZjI9/e4j1oxVcWwdyIu5ci/IKRhOWcqcfg//GO1wSw4SEb3HZB3SfNnAggpZ3i2W7I7SpAyxcj7ljmEu67tDkSvYThSmx33QrD1EKb49A5gJaMAED8xfBTHTfLuTfGMAwmJLSss9sc=,iv:I9sn3mA3VkLRFAq+PR6Vi2sh9aeAuQg7FwPRGFnR2Oo=,tag:9LtsbfTv88qNoJaZQq25mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
