---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.15.2
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      interval: 5m

  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 5
  uninstall:
    keepHistory: false

  values:
    crds:
      enabled: true
    pspEnable: false
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
