apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
    namespace: rook-ceph
stringData:
    password: ENC[AES256_GCM,data:i+Hjc53Vzd8s9AO812YTeT3XUphf1Lfj,iv:vaQppaHAaIMI0Nl3SprBNNJ3Ky9wdX52m5gMnHKOBPQ=,tag:PKdsHcjyc7Jx7Y1mobqWNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8umafmvdenl8r9xwnx458lua7wlwd7qthr2g4j4pxay4p2w6qrs406qmy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhWZXZXU2tPcVhGUVFN
            MjhZWU51M3ltTDNJcGtXWSt4TjlGMmtaTkhzClQ0TU1ZTHYwcUE4d2FQeTZleTJU
            dFAzL0ZSQkJVZ0RiTDZuSlNuV09Qck0KLS0tIG5tWnBrYnpta2JMMjlvU3ZaZkVE
            aTJiVDQrNEFrcmphQllSemVoUW4wWmcKuYowXh/u9jhxhH2eJSk7x2UAsZi+jA2O
            nYMOTDdNIzuSsOI2969MCVdlLFyn8t6pxESDBPROsu4FegZrRveM6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T19:58:59Z"
    mac: ENC[AES256_GCM,data:LYlTzwVKdSguKp4mSBu/K/4+u1c17bUV9cwD3MrNH+Sx/4pszc8sI1fnQsn5VTuH/c1rNN4yjVPXYVUq2I6zV9HU9We4bbML/5TnsKtZ+ckb1hLq9CCQWlr28IZNzNJGLRXcrWkGdLg9az743ZyyE1L0LSol7VqfMSucNOz/zYs=,iv:N5zyAgNUoYVX/xjst1x9+iCUc/J0hoitlDzxQS0dtR0=,tag:Bd5QlDCzkSgx6disz2Q3sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
