---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        env:
          - name: INIT_POSTGRES_HOST
            value: ${POSTGRES_HOST}
          - name: INIT_POSTGRES_DBNAME
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: PAPERLESS_DBNAME
          - name: INIT_POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: INIT_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: PAPERLESS_DBUSER
          - name: INIT_POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: paperless-secret
                key: PAPERLESS_DBPASS

